/* 261009-tgw fragment: es (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    es: {
      title: 'Grupos cíclicos — Visualizador de collares',
      eyebrow: 'teoría de grupos · generadores y órbitas',
      heading: 'Collar del grupo cíclico',
      lede: 'Elige un grupo. Cada elemento se coloca en un círculo, a distancias iguales. Avanzar con el generador dibuja las cuerdas, y un generador que alcanza todos los elementos es lo que hace cíclico al grupo. Los grupos sin un elemento así se dividen en los círculos con los que están construidos.',
      xref: 'Mira la tabla de operación completa de este grupo en la Tabla de Cayley →',
      tablistLabel: 'Operación de grupo',
      groupHeading: 'Grupo',
      subgroupHeading: 'Subgrupo',
      identityOnly: 'El elemento identidad solo produce a sí mismo',
      nLabel: 'n — módulo',
      genLabel: 'Subgrupo visualizado',
      nNoteClamped: 'n va de 2 a 100, así que el diagrama muestra n = {n}.',
      layersHeading: 'Capas',
      extraOptions: 'Mostrar opciones adicionales',
      layerCord: 'Mostrar el polígono correspondiente',
      layerGuide: 'Mostrar el círculo que une los elementos',
      layerElement: 'Camino de ida',
      layerElementTitle: 'Dar un paso es combinar el elemento actual con {g}',
      layerBackward: 'Desactivar el camino de vuelta',
      layerPaths: 'Caminos del subgrupo',
      resizeTitle: 'Arrastra para cambiar el tamaño; haz doble clic para restablecerlo',
      dirLabel: 'Dirección de ida',
      dirCw: 'En sentido horario',
      dirCcw: 'En sentido antihorario',
      sideInside: 'Dentro',
      sideOutside: 'Fuera',
      colorElement: 'Color de la flecha del elemento',
      colorInverse: 'Color de la flecha del inverso',
      colorReset: 'Reiniciar los colores de las flechas',
      genTop: 'Girar el generador seleccionado hacia arriba',
      swapColors: 'Intercambiar los colores de los caminos de ida y de vuelta',
      customColors: 'Elegir los colores de las flechas manualmente',
      layerColors: 'Colores de los elementos',
      colorByLabel: 'Colorear los elementos según',
      colorByOrder: 'Cardinalidad del subgrupo',
      colorByInverse: 'Pares de inversos',
      layerOrders: 'Etiquetas de orden',
      layerBygen: 'Organizar los elementos por potencias del generador',
      combineForward: 'Camino de ida, combinando los elementos con el elemento seleccionado {h}',
      combineBackward: 'Camino de vuelta, combinando los elementos con el inverso del elemento seleccionado, que es {hinv}',
      combineSelfInverse: '{h} es su propio inverso, así que los dos recorridos son el mismo, dibujado una sola vez con una mezcla de los dos colores',
      factsHeading: 'Este grupo',
      cosetButton: 'Explorar clases laterales',
      cosetHide: 'Dejar de explorar clases laterales',
      cosetNoneGenerator: 'No hay clases laterales que explorar; {g} es un generador',
      cosetProgress: 'Resaltando ahora la clase lateral {i} de {count}',
      autoRotate: 'Giro automático',
      autoRotateOff: 'Desactivado',
      autoRotateCcw: 'En sentido antihorario',
      autoRotateCw: 'En sentido horario',
      rotateLabel: 'Giro — arrastra el círculo',
      rotateBack: 'Girar un elemento en sentido antihorario',
      rotateForward: 'Girar un elemento en sentido horario',
      rotateValue: 'Giro en pasos',
      rotateReset: 'Reiniciar',
      subgroupsHeading: 'Subgrupo generado por cada elemento',
      autoShift: 'Desplazar automáticamente los subgrupos cíclicos',
      autoShiftTitle: 'Desplaza automáticamente el subgrupo cíclico generado para que coincida con el primer elemento desde arriba al avanzar en la dirección de ida',
      subLayoutLabel: 'Disposición',
      subLayoutGrid: 'Cuadrícula',
      subLayoutList: 'Lista',
      'fact.group': 'Grupo',
      'fact.elements': 'Elementos',
      'fact.identity': 'Identidad',
      'fact.operation': 'Operación',
      opAdd: 'suma módulo {n}',
      opMul: 'multiplicación módulo {n}',
      'fact.generators': 'Generadores',
      'fact.structure': 'Estructura',
      factGeneratorsCount: '{count} de {order}',
      factGeneratorsNone: '0 (no cíclico)',
      'hint.notCyclic': 'Ningún elemento recorre a todos los demás: las flechas desde 1 siempre vuelven antes de que el círculo se llene.',
      'hint.noLabels': 'Los elementos son demasiado pequeños para mostrar etiquetas numéricas aquí; el patrón se sigue viendo.',
      'hint.multiplicative': 'Los elementos son los números menores que {n} que no comparten ningún factor con él. Avanzar significa multiplicar por {g} módulo {n}.',
      'hint.additive': 'Avanzar significa sumar {g} módulo {n}.',
      'hint.mirror': 'Los inversos se reflejan entre sí a ambos lados del eje discontinuo que pasa por la identidad; el elemento que está sobre el eje es su propio inverso.',
      'hint.mirrorOffSorted': 'Los elementos están ordenados por valor, así que aquí los inversos no se reflejan.',
      'hint.mirrorOff': 'Con esta disposición los elementos están ordenados por valor, así que los inversos no se reflejan. Activa “Organizar los elementos por potencias del generador” para verlos reflejarse a ambos lados del eje que pasa por la identidad.',
      legendHeading: 'Clave de colores: cardinalidad del subgrupo',
      legendOrder: 'Cardinalidad del subgrupo: {order}',
      legendSubgroups: { one: '{count} subgrupo', other: '{count} subgrupos' },
      legendHeadingInverse: 'Clave de colores: pares de inversos',
      legendSelfInverse: 'su propio inverso: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · elemento {h} de orden {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, así que hay {n} / {size} = {count} clases laterales',
      ringFootnote: 'La identidad, {id}, está rodeada con un círculo.',
      ringFootnoteOrders: 'La identidad, {id}, está rodeada con un círculo; el número pequeño exterior es el orden de cada elemento.',
      svgAriaLabel: 'Diagrama de collar de {group}',
      'notice.heading': '{group} no tiene generador, así que ningún recorrido alcanza todos los elementos',
      'notice.body': 'El grupo tiene {count} elementos, pero ningún elemento por sí solo los alcanza todos: el recorrido más largo desde 1 da {longest} pasos. El grupo está construido a partir de los grupos cíclicos {factors}.',
      'notice.whyPowerOfTwo': 'Por qué: n = {n} es una potencia de 2 mayor que 4.',
      'notice.whyFourAndOdd': 'Por qué: n = {n} es divisible por 4 y por un primo impar.',
      'notice.whyTwoOddPrimes': 'Por qué: n = {n} tiene dos factores primos impares distintos.',
      'notice.rule': '(Z/n)* es cíclico exactamente cuando n es 1, 2 o 4, una potencia de un primo impar p^k, o el doble de una, 2p^k. El grupo aditivo Z/n siempre es cíclico.',
      exportPng: 'Descargar PNG del círculo',
      exportSaved: 'Guardado: {filename}.',
      exportFailed: 'No se pudo exportar la imagen en este navegador.'
    }
});
NT.i18n.register('site', {
    es: {
      'nav.cyclicGroups': 'Grupos cíclicos'
    }
});
NT.i18n.register('hub', {
    es: {
      'card.cyclicGroups.title': 'Collar del grupo cíclico',
      'card.cyclicGroups.desc': 'Cada elemento de un grupo se convierte en una cuenta sobre un círculo; avanza con un generador y las cuerdas trazan una estrella que toca todas las cuentas — y cuando ningún elemento por sí solo puede alcanzarlas todas, el grupo se divide en los círculos más pequeños con los que está construido.'
    }
});
