/* 261009-tgw fragment: fr (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    fr: {
      title: 'Groupes cycliques — Visualiseur en collier',
      eyebrow: 'théorie des groupes · générateurs et orbites',
      heading: 'Collier du groupe cyclique',
      lede: 'Choisissez un groupe. Chaque élément prend place sur un cercle, à intervalles réguliers. Avancer par le générateur trace les cordes, et un générateur qui atteint tous les éléments est ce qui rend le groupe cyclique. Les groupes sans tel élément se décomposent en les cercles dont ils sont constitués.',
      xref: 'Voir la table d’opération complète de ce groupe dans la Table de Cayley →',
      tablistLabel: 'Opération de groupe',
      groupHeading: 'Groupe',
      subgroupHeading: 'Sous-groupe',
      identityOnly: 'L’élément neutre n’engendre que lui-même',
      nLabel: 'n — module',
      genLabel: 'Sous-groupe visualisé',
      nNoteClamped: 'n varie de 2 à 100, donc le diagramme affiche n = {n}.',
      layersHeading: 'Couches',
      extraOptions: 'Afficher les options supplémentaires',
      layerCord: 'Afficher le polygone correspondant',
      layerGuide: 'Afficher le cercle qui relie les éléments',
      layerElement: 'Chemin aller',
      layerElementTitle: 'Faire un pas, c’est combiner l’élément courant avec {g}',
      layerBackward: 'Désactiver le chemin retour',
      layerPaths: 'Chemins du sous-groupe',
      resizeTitle: 'Faites glisser pour redimensionner ; double-cliquez pour réinitialiser',
      dirLabel: 'Sens aller',
      dirCw: 'Sens horaire',
      dirCcw: 'Sens antihoraire',
      sideInside: 'À l’intérieur',
      sideOutside: 'À l’extérieur',
      colorElement: 'Couleur de la flèche de l’élément',
      colorInverse: 'Couleur de la flèche de l’inverse',
      colorReset: 'Réinitialiser les couleurs des flèches',
      genTop: 'Tourner le générateur sélectionné vers le haut',
      swapColors: 'Échanger les couleurs des chemins aller et retour',
      customColors: 'Choisir les couleurs des flèches manuellement',
      layerColors: 'Couleurs des éléments',
      colorByLabel: 'Colorer les éléments selon',
      colorByOrder: 'Cardinal du sous-groupe',
      colorByInverse: 'Paires d’inverses',
      layerOrders: 'Étiquettes d’ordre',
      layerBygen: 'Disposer les éléments selon les puissances du générateur',
      combineForward: 'Chemin aller, en combinant les éléments avec l’élément sélectionné {h}',
      combineBackward: 'Chemin retour, en combinant les éléments avec l’inverse de l’élément sélectionné, qui est {hinv}',
      combineSelfInverse: '{h} est son propre inverse, donc les deux parcours n’en font qu’un, tracé une seule fois dans un mélange des deux couleurs',
      factsHeading: 'Ce groupe',
      cosetButton: 'Explorer les classes latérales',
      cosetHide: 'Arrêter d’explorer les classes latérales',
      cosetNoneGenerator: 'Aucune classe latérale à explorer ; {g} est un générateur',
      cosetProgress: 'Mise en évidence de la classe latérale {i} sur {count}',
      autoRotate: 'Rotation automatique',
      autoRotateOff: 'Désactivée',
      autoRotateCcw: 'Sens antihoraire',
      autoRotateCw: 'Sens horaire',
      rotateLabel: 'Rotation — faites glisser le cercle',
      rotateBack: 'Tourner d’un élément dans le sens antihoraire',
      rotateForward: 'Tourner d’un élément dans le sens horaire',
      rotateValue: 'Rotation en pas',
      rotateReset: 'Réinitialiser',
      subgroupsHeading: 'Sous-groupe engendré par chaque élément',
      autoShift: 'Décaler automatiquement les sous-groupes cycliques',
      autoShiftTitle: 'Décale automatiquement le sous-groupe cyclique engendré pour qu’il corresponde au premier élément en partant du haut, dans le sens aller',
      subLayoutLabel: 'Affichage',
      subLayoutGrid: 'Grille',
      subLayoutList: 'Liste',
      'fact.group': 'Groupe',
      'fact.elements': 'Éléments',
      'fact.identity': 'Élément neutre',
      'fact.operation': 'Opération',
      opAdd: 'addition modulo {n}',
      opMul: 'multiplication modulo {n}',
      'fact.generators': 'Générateurs',
      'fact.structure': 'Structure',
      factGeneratorsCount: '{count} sur {order}',
      factGeneratorsNone: '0 (non cyclique)',
      'hint.notCyclic': 'Aucun élément ne parcourt tous les autres : les flèches issues de 1 reviennent toujours avant que le cercle ne soit complet.',
      'hint.noLabels': 'Les éléments sont trop petits pour afficher des étiquettes numériques ici ; le motif reste visible.',
      'hint.multiplicative': 'Les éléments sont les nombres inférieurs à {n} qui n’ont aucun facteur commun avec lui. Avancer revient à multiplier par {g} modulo {n}.',
      'hint.additive': 'Avancer revient à ajouter {g} modulo {n}.',
      'hint.mirror': 'Les inverses se reflètent de part et d’autre de l’axe en pointillés passant par l’élément neutre ; l’élément situé sur l’axe est son propre inverse.',
      'hint.mirrorOffSorted': 'Les éléments sont triés par valeur, donc les inverses ne se reflètent pas ici.',
      'hint.mirrorOff': 'Avec cette disposition, les éléments sont triés par valeur, donc les inverses ne se reflètent pas. Activez « Disposer les éléments selon les puissances du générateur » pour les voir se refléter de part et d’autre de l’axe passant par l’élément neutre.',
      legendHeading: 'Légende des couleurs : cardinal du sous-groupe',
      legendOrder: 'Cardinal du sous-groupe : {order}',
      legendSubgroups: { one: '{count} sous-groupe', other: '{count} sous-groupes' },
      legendHeadingInverse: 'Légende des couleurs : paires d’inverses',
      legendSelfInverse: 'auto-inverses : {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · élément {h} d’ordre {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, donc il y a {n} / {size} = {count} classes latérales',
      ringFootnote: 'L’élément neutre, {id}, est entouré d’un cercle.',
      ringFootnoteOrders: 'L’élément neutre, {id}, est entouré d’un cercle ; le petit nombre extérieur est l’ordre de chaque élément.',
      svgAriaLabel: 'Diagramme en collier de {group}',
      'notice.heading': '{group} n’a pas de générateur, donc aucun parcours n’atteint tous les éléments',
      'notice.body': 'Le groupe compte {count} éléments, mais aucun élément seul ne les atteint tous : le plus long parcours depuis 1 compte {longest} pas. Le groupe est construit à partir des groupes cycliques {factors}.',
      'notice.whyPowerOfTwo': 'Raison : n = {n} est une puissance de 2 supérieure à 4.',
      'notice.whyFourAndOdd': 'Raison : n = {n} est divisible par 4 et par un nombre premier impair.',
      'notice.whyTwoOddPrimes': 'Raison : n = {n} a deux facteurs premiers impairs distincts.',
      'notice.rule': '(Z/n)* est cyclique exactement lorsque n vaut 1, 2 ou 4, une puissance d’un nombre premier impair p^k, ou le double d’une telle puissance, 2p^k. Le groupe additif Z/n est toujours cyclique.',
      exportPng: 'Télécharger le PNG du cercle',
      exportSaved: 'Enregistré : {filename}.',
      exportFailed: 'L’image n’a pas pu être exportée dans ce navigateur.'
    }
});
NT.i18n.register('site', {
    fr: {
      'nav.cyclicGroups': 'Groupes cycliques'
    }
});
NT.i18n.register('hub', {
    fr: {
      'card.cyclicGroups.title': 'Collier du groupe cyclique',
      'card.cyclicGroups.desc': 'Chaque élément d’un groupe devient une perle sur un cercle ; avancez par un générateur et les cordes tracent une étoile qui touche chaque perle — et lorsqu’aucun élément ne peut les atteindre toutes, le groupe se divise en les cercles plus petits dont il est constitué.'
    }
});
