/* 261009-tgw fragment: he (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    he: {
      title: 'חבורות ציקליות — הדמיית שרשרת',
      eyebrow: 'תורת החבורות · יוצרים ומסלולים',
      heading: 'שרשרת חבורה ציקלית',
      lede: 'בחרו חבורה. כל איבר יושב על טבעת במרווחים שווים. הליכה בצעדי היוצר מציירת את המיתרים, ויוצר שמגיע לכל איבר הוא מה שהופך את החבורה לציקלית. חבורות שאין בהן איבר כזה מתפצלות לטבעות שמהן הן בנויות.',
      xref: 'ראו את טבלת הפעולה המלאה של החבורה הזו בטבלת קיילי ←',
      tablistLabel: 'פעולת החבורה',
      groupHeading: 'חבורה',
      subgroupHeading: 'תת-חבורה',
      identityOnly: 'איבר היחידה יוצר רק את עצמו',
      nLabel: 'n — מודולוס',
      genLabel: 'תת-החבורה המוצגת',
      nNoteClamped: 'n נע בין 2 ל-100, ולכן הדיאגרמה מציגה \u2066n = {n}\u2069.',
      layersHeading: 'שכבות',
      extraOptions: 'הצגת אפשרויות נוספות',
      layerCord: 'הצגת המצולע המתאים',
      layerGuide: 'הצגת המעגל המחבר',
      layerElement: 'מסלול קדימה',
      layerElementTitle: 'צעד פירושו שילוב של האיבר הנוכחי עם {g}',
      layerBackward: 'השבתת מסלול אחורה',
      layerPaths: 'מסלולי תת-החבורה',
      resizeTitle: 'גררו לשינוי הגודל; לחיצה כפולה לאיפוס',
      dirLabel: 'כיוון קדימה',
      dirCw: 'עם כיוון השעון',
      dirCcw: 'נגד כיוון השעון',
      sideInside: 'בפנים',
      sideOutside: 'בחוץ',
      colorElement: 'צבע חץ האיבר',
      colorInverse: 'צבע חץ ההופכי',
      colorReset: 'איפוס צבעי החצים',
      genTop: 'סיבוב היוצר שנבחר לראש',
      swapColors: 'החלפת הצבעים של מסלול קדימה ושל מסלול אחורה',
      customColors: 'בחירה ידנית של צבעי החצים',
      layerColors: 'צבעי האיברים',
      colorByLabel: 'צביעת האיברים לפי',
      colorByOrder: 'עוצמת תת-החבורה',
      colorByInverse: 'זוגות הופכיים',
      layerOrders: 'תוויות סדר',
      layerBygen: 'סידור האיברים לפי חזקות היוצר',
      combineForward: 'מסלול קדימה, בשילוב האיברים עם האיבר שנבחר {h}',
      combineBackward: 'מסלול אחורה, בשילוב האיברים עם ההופכי של האיבר שנבחר, שהוא {hinv}',
      combineSelfInverse: '{h} הוא ההופכי של עצמו, ולכן שתי ההליכות הן אותה הליכה, המצוירת פעם אחת בתערובת של שני הצבעים',
      factsHeading: 'החבורה הזו',
      cosetButton: 'חקירת קוסטים',
      cosetHide: 'הפסקת חקירת הקוסטים',
      cosetNoneGenerator: 'אין קוסטים לחקור; {g} הוא יוצר',
      cosetProgress: 'מודגש כעת קוסט {i} מתוך {count}',
      autoRotate: 'סיבוב אוטומטי',
      autoRotateOff: 'כבוי',
      autoRotateCcw: 'נגד כיוון השעון',
      autoRotateCw: 'עם כיוון השעון',
      rotateLabel: 'סיבוב — גררו את הטבעת',
      rotateBack: 'סיבוב איבר אחד נגד כיוון השעון',
      rotateForward: 'סיבוב איבר אחד עם כיוון השעון',
      rotateValue: 'סיבוב בצעדים',
      rotateReset: 'איפוס',
      subgroupsHeading: 'תת-החבורה שנוצרת על ידי כל איבר',
      autoShift: 'הזזה אוטומטית של תת-חבורות ציקליות',
      autoShiftTitle: 'הזזה אוטומטית של תת-החבורה הציקלית שנוצרה, כך שתתאים לאיבר הראשון מלמעלה בכיוון קדימה',
      subLayoutLabel: 'פריסה',
      subLayoutGrid: 'רשת',
      subLayoutList: 'רשימה',
      'fact.group': 'חבורה',
      'fact.elements': 'איברים',
      'fact.identity': 'איבר היחידה',
      'fact.operation': 'פעולה',
      opAdd: 'חיבור מודולו {n}',
      opMul: 'כפל מודולו {n}',
      'fact.generators': 'יוצרים',
      'fact.structure': 'מבנה',
      factGeneratorsCount: '{count} מתוך {order}',
      factGeneratorsNone: '0 (לא ציקלית)',
      'hint.notCyclic': 'אין איבר שמגיע בהליכה לכל שאר האיברים: החצים היוצאים מ-1 תמיד חוזרים לפני שהטבעת מתמלאת.',
      'hint.noLabels': 'האיברים קטנים מכדי להציג כאן תוויות מספרים; התבנית עדיין נראית.',
      'hint.multiplicative': 'האיברים הם המספרים הקטנים מ-{n} שאין להם גורם משותף איתו. צעד פירושו כפל ב-{g} מודולו {n}.',
      'hint.additive': 'צעד פירושו חיבור של {g} מודולו {n}.',
      'hint.mirror': 'ההופכיים משתקפים זה בזה משני צדי הציר המקווקו העובר באיבר היחידה; האיבר שעל הציר הוא ההופכי של עצמו.',
      'hint.mirrorOffSorted': 'האיברים ממוינים לפי ערך, ולכן ההופכיים אינם משתקפים כאן.',
      'hint.mirrorOff': 'בסדר הזה האיברים ממוינים לפי ערך, ולכן ההופכיים אינם משתקפים. הפעילו את "סידור האיברים לפי חזקות היוצר" כדי לראות אותם משתקפים משני צדי הציר העובר באיבר היחידה.',
      legendHeading: 'מקרא צבעים: עוצמת תת-החבורה',
      legendOrder: 'עוצמת תת-החבורה: {order}',
      legendSubgroups: { one: '{count} תת-חבורה', two: '{count} תת-חבורות', other: '{count} תת-חבורות' },
      legendHeadingInverse: 'מקרא צבעים: זוגות הופכיים',
      legendSelfInverse: 'הופכי של עצמו: \u2066{list}\u2069',
      legendPair: '\u2066{a} ↔ {b}\u2069',
      ringTitle: '\u2066{group}\u2069 · איבר {h} מסדר {k}',
      cosetTitleAdd: '\u2066{a} + ⟨{h}⟩ = {set}\u2069',
      cosetTitleMul: '\u2066{a} · ⟨{h}⟩ = {set}\u2069',
      cosetCountAdd: '\u2066|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}\u2069, ולכן יש \u2066{n} / {size} = {count}\u2069 קוסטים',
      ringFootnote: 'איבר היחידה, {id}, מוקף בטבעת.',
      ringFootnoteOrders: 'איבר היחידה, {id}, מוקף בטבעת; המספר הקטן שבחוץ הוא הסדר של כל איבר.',
      svgAriaLabel: 'דיאגרמת שרשרת של \u2066{group}\u2069',
      'notice.heading': 'אין יוצר ל-\u2066{group}\u2069, ולכן אין הליכה שמגיעה לכל איבר',
      'notice.body': 'בחבורה יש {count} איברים, אבל אין איבר בודד שמגיע לכולם: ההליכה הארוכה ביותר מ-1 נמשכת {longest} צעדים. החבורה בנויה מהחבורות הציקליות \u2066{factors}\u2069.',
      'notice.whyPowerOfTwo': 'הסיבה: \u2066n = {n}\u2069 הוא חזקה של 2 הגדולה מ-4.',
      'notice.whyFourAndOdd': 'הסיבה: \u2066n = {n}\u2069 מתחלק ב-4 וגם במספר ראשוני אי-זוגי.',
      'notice.whyTwoOddPrimes': 'הסיבה: ל-\u2066n = {n}\u2069 יש שני גורמים ראשוניים אי-זוגיים שונים.',
      'notice.rule': '\u2066(Z/n)*\u2069 ציקלית בדיוק כאשר n הוא 1, 2 או 4, חזקה של ראשוני אי-זוגי \u2066p^k\u2069, או כפולה שלה פי שניים, \u20662p^k\u2069. החבורה החיבורית \u2066Z/n\u2069 תמיד ציקלית.',
      exportPng: 'הורדת PNG של הטבעת',
      exportSaved: 'נשמר \u2066{filename}\u2069.',
      exportFailed: 'לא ניתן היה לייצא את התמונה בדפדפן הזה.'
    }
});
NT.i18n.register('site', {
    he: {
      'nav.cyclicGroups': 'חבורות ציקליות'
    }
});
NT.i18n.register('hub', {
    he: {
      'card.cyclicGroups.title': 'שרשרת חבורה ציקלית',
      'card.cyclicGroups.desc': 'כל איבר בחבורה הופך לחרוז על טבעת; צעדו בצעדי יוצר והמיתרים משרטטים כוכב שנוגע בכל חרוז — וכשאף איבר בודד אינו יכול להגיע לכולם, החבורה מתפצלת לטבעות הקטנות שמהן היא בנויה.'
    }
});
