/* 261009-tgw fragment: hu (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    hu: {
      title: 'Ciklikus csoportok — nyaklánc-vizualizáló',
      eyebrow: 'csoportelmélet · generátorok és pályák',
      heading: 'Ciklikus csoport nyaklánca',
      lede: 'Válassz egy csoportot. Minden elem egy körön ül, egyenlő távolságra egymástól. A generátorral lépkedve megrajzolódnak a húrok, és az a generátor, amely minden elemet elér, teszi a csoportot ciklikussá. Az olyan csoportok, amelyekben nincs ilyen elem, felbomlanak azokra a körökre, amelyekből felépülnek.',
      xref: 'Ennek a csoportnak a teljes műveleti táblázatát a Cayley-táblázatban találod →',
      tablistLabel: 'Csoportművelet',
      groupHeading: 'Csoport',
      subgroupHeading: 'Részcsoport',
      identityOnly: 'Az egységelem csak önmagát állítja elő',
      nLabel: 'n — modulus',
      genLabel: 'Megjelenített részcsoport',
      nNoteClamped: 'n értéke 2 és 100 között lehet, ezért az ábra n = {n} esetet mutatja.',
      layersHeading: 'Rétegek',
      extraOptions: 'További beállítások megjelenítése',
      layerCord: 'A megfelelő sokszög megjelenítése',
      layerGuide: 'Az összekötő kör megjelenítése',
      layerElement: 'Előre vezető út',
      layerElementTitle: 'Egy lépés: az aktuális elem összekapcsolása ezzel: {g}',
      layerBackward: 'Visszafelé vezető út kikapcsolása',
      layerPaths: 'A részcsoport útjai',
      resizeTitle: 'Húzd az átméretezéshez; kattints duplán a visszaállításhoz',
      dirLabel: 'Előre irány',
      dirCw: 'Óramutató járásával megegyező',
      dirCcw: 'Óramutató járásával ellentétes',
      sideInside: 'Belül',
      sideOutside: 'Kívül',
      colorElement: 'Az elem nyilainak színe',
      colorInverse: 'Az inverz nyilainak színe',
      colorReset: 'Nyílszínek visszaállítása',
      genTop: 'A kiválasztott generátor forgatása felülre',
      swapColors: 'Az előre és a visszafelé vezető út színének felcserélése',
      customColors: 'A nyílszínek kézi kiválasztása',
      layerColors: 'Elemszínek',
      colorByLabel: 'Az elemek színezése ez alapján',
      colorByOrder: 'Részcsoport számossága',
      colorByInverse: 'Inverzpárok',
      layerOrders: 'Rendcímkék',
      layerBygen: 'Elemek rendezése a generátor hatványai szerint',
      combineForward: 'Előre vezető út, az elemeket a kiválasztott elemmel ({h}) összekapcsolva',
      combineBackward: 'Visszafelé vezető út, az elemeket a kiválasztott elem inverzével összekapcsolva, ami {hinv}',
      combineSelfInverse: '{h} önmagával inverz, ezért a két bejárás ugyanaz, egyszer rajzolva, a két szín keverékével',
      factsHeading: 'Ez a csoport',
      cosetButton: 'Mellékosztályok felfedezése',
      cosetHide: 'Mellékosztályok felfedezésének leállítása',
      cosetNoneGenerator: 'Nincs felfedezhető mellékosztály, mert {g} generátor',
      cosetProgress: 'Kiemelt mellékosztály: {i} / {count}',
      autoRotate: 'Automatikus forgatás',
      autoRotateOff: 'Ki',
      autoRotateCcw: 'Óramutató járásával ellentétes',
      autoRotateCw: 'Óramutató járásával megegyező',
      rotateLabel: 'Forgatás — húzd a kört',
      rotateBack: 'Forgatás egy elemmel az óramutató járásával ellentétesen',
      rotateForward: 'Forgatás egy elemmel az óramutató járásával megegyezően',
      rotateValue: 'Forgatás lépésekben',
      rotateReset: 'Visszaállítás',
      subgroupsHeading: 'Az egyes elemek által generált részcsoport',
      autoShift: 'Ciklikus részcsoportok automatikus eltolása',
      autoShiftTitle: 'A generált ciklikus részcsoport automatikus eltolása úgy, hogy az előre irányban haladva a felülről első elemhez igazodjon',
      subLayoutLabel: 'Elrendezés',
      subLayoutGrid: 'Rács',
      subLayoutList: 'Lista',
      'fact.group': 'Csoport',
      'fact.elements': 'Elemek',
      'fact.identity': 'Egységelem',
      'fact.operation': 'Művelet',
      opAdd: 'összeadás mod {n}',
      opMul: 'szorzás mod {n}',
      'fact.generators': 'Generátorok',
      'fact.structure': 'Szerkezet',
      factGeneratorsCount: '{count} / {order}',
      factGeneratorsNone: '0 (nem ciklikus)',
      'hint.notCyclic': 'Nincs olyan elem, amely az összes többit elérné: az 1-ből induló nyilak mindig visszatérnek, mielőtt a kör megtelne.',
      'hint.noLabels': 'Az elemek itt túl kicsik a számfeliratokhoz; a minta így is látszik.',
      'hint.multiplicative': 'Az elemek azok a számok {n} alatt, amelyeknek nincs vele közös tényezőjük. A lépés szorzást jelent, a szorzó {g}, mod {n}.',
      'hint.additive': 'A lépés összeadást jelent, az összeadandó {g}, mod {n}.',
      'hint.mirror': 'Az inverzek tükrözik egymást az egységelemen átmenő szaggatott tengelyre; a tengelyen lévő elem önmagával inverz.',
      'hint.mirrorOffSorted': 'Az elemek érték szerint vannak rendezve, ezért az inverzek itt nem tükrözik egymást.',
      'hint.mirrorOff': 'Ebben a sorrendben az elemek érték szerint vannak rendezve, ezért az inverzek nem tükrözik egymást. Kapcsold be az „Elemek rendezése a generátor hatványai szerint” opciót, hogy lásd, ahogy az egységelemen átmenő tengelyre tükröződnek.',
      legendHeading: 'Színkulcs: részcsoport számossága',
      legendOrder: 'A részcsoport számossága: {order}',
      legendSubgroups: { one: '{count} részcsoport', other: '{count} részcsoport' },
      legendHeadingInverse: 'Színkulcs: inverzpárok',
      legendSelfInverse: 'önmagával inverz: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · {h} elem, rendje {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, tehát a mellékosztályok száma {n} / {size} = {count}',
      ringFootnote: 'Az egységelem, {id}, be van karikázva.',
      ringFootnoteOrders: 'Az egységelem, {id}, be van karikázva; a kis külső szám az egyes elemek rendje.',
      svgAriaLabel: 'Nyakláncdiagram: {group}',
      'notice.heading': '{group}: nincs generátor, ezért nincs olyan bejárás, amely minden elemet elérne',
      'notice.body': 'A csoportnak {count} eleme van, de egyetlen elem sem éri el mindet: az 1-ből induló leghosszabb bejárás hossza {longest}. A csoport a következő ciklikus csoportokból épül fel: {factors}.',
      'notice.whyPowerOfTwo': 'Ok: n = {n} a 2 egy 4-nél nagyobb hatványa.',
      'notice.whyFourAndOdd': 'Ok: n = {n} osztható 4-gyel és egy páratlan prímmel.',
      'notice.whyTwoOddPrimes': 'Ok: az n = {n} számnak két különböző páratlan prímtényezője van.',
      'notice.rule': '(Z/n)* pontosan akkor ciklikus, ha n értéke 1, 2 vagy 4, egy páratlan prím p^k hatványa, vagy annak kétszerese, 2p^k. Az additív Z/n mindig ciklikus.',
      exportPng: 'Kör PNG letöltése',
      exportSaved: '{filename} mentve.',
      exportFailed: 'A kép ebben a böngészőben nem exportálható.'
    }
});
NT.i18n.register('site', {
    hu: {
      'nav.cyclicGroups': 'Ciklikus csoportok'
    }
});
NT.i18n.register('hub', {
    hu: {
      'card.cyclicGroups.title': 'Ciklikus csoport nyaklánca',
      'card.cyclicGroups.desc': 'Egy csoport minden eleme egy gyöngy lesz egy körön; lépj egy generátorral, és a húrok olyan csillagot rajzolnak, amely minden gyöngyöt érint — és ha egyetlen elem sem éri el mindet, a csoport felbomlik azokra a kisebb körökre, amelyekből felépül.'
    }
});
