/* 261009-tgw fragment: id (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    id: {
      title: 'Grup Siklik — Visualisasi Kalung',
      eyebrow: 'teori grup · pembangkit dan orbit',
      heading: 'Kalung Grup Siklik',
      lede: 'Pilih sebuah grup. Setiap elemen berada pada sebuah cincin dengan jarak yang sama. Melangkah dengan pembangkit menggambar tali busur, dan pembangkit yang mencapai setiap elemen itulah yang membuat grup menjadi siklik. Grup yang tidak punya elemen seperti itu dipecah menjadi cincin-cincin penyusunnya.',
      xref: 'Lihat tabel operasi lengkap grup ini di Tabel Cayley →',
      tablistLabel: 'Operasi grup',
      groupHeading: 'Grup',
      subgroupHeading: 'Subgrup',
      identityOnly: 'Elemen identitas hanya menghasilkan dirinya sendiri',
      nLabel: 'n — modulus',
      genLabel: 'Subgrup yang divisualisasikan',
      nNoteClamped: 'n berkisar dari 2 sampai 100, sehingga diagram menampilkan n = {n}.',
      layersHeading: 'Lapisan',
      extraOptions: 'Tampilkan opsi tambahan',
      layerCord: 'Tampilkan poligon yang sesuai',
      layerGuide: 'Tampilkan lingkaran penghubung',
      layerElement: 'Lintasan maju',
      layerElementTitle: 'Melangkah berarti menggabungkan elemen saat ini dengan {g}',
      layerBackward: 'Nonaktifkan lintasan mundur',
      layerPaths: 'Lintasan subgrup',
      resizeTitle: 'Seret untuk mengubah ukuran; klik dua kali untuk mengatur ulang',
      dirLabel: 'Arah maju',
      dirCw: 'Searah jarum jam',
      dirCcw: 'Berlawanan arah jarum jam',
      sideInside: 'Di dalam',
      sideOutside: 'Di luar',
      colorElement: 'Warna panah elemen',
      colorInverse: 'Warna panah invers',
      colorReset: 'Atur ulang warna panah',
      genTop: 'Putar pembangkit yang dipilih ke atas',
      swapColors: 'Tukar warna lintasan maju dan mundur',
      customColors: 'Pilih warna panah secara manual',
      layerColors: 'Warna elemen',
      colorByLabel: 'Warnai elemen berdasarkan',
      colorByOrder: 'Kardinalitas subgrup',
      colorByInverse: 'Pasangan invers',
      layerOrders: 'Label orde',
      layerBygen: 'Susun elemen menurut pangkat pembangkit',
      combineForward: 'Lintasan maju, menggabungkan elemen dengan elemen terpilih {h}',
      combineBackward: 'Lintasan mundur, menggabungkan elemen dengan invers elemen terpilih, yaitu {hinv}',
      combineSelfInverse: '{h} adalah inversnya sendiri, sehingga kedua langkah itu sama, digambar sekali dengan campuran kedua warna',
      factsHeading: 'Grup ini',
      cosetButton: 'Jelajahi koset',
      cosetHide: 'Berhenti menjelajahi koset',
      cosetNoneGenerator: 'Tidak ada koset untuk dijelajahi; {g} adalah pembangkit',
      cosetProgress: 'Saat ini menyorot koset {i} dari {count}',
      autoRotate: 'Putar otomatis',
      autoRotateOff: 'Mati',
      autoRotateCcw: 'Berlawanan arah jarum jam',
      autoRotateCw: 'Searah jarum jam',
      rotateLabel: 'Rotasi — seret cincin',
      rotateBack: 'Putar satu elemen berlawanan arah jarum jam',
      rotateForward: 'Putar satu elemen searah jarum jam',
      rotateValue: 'Rotasi dalam langkah',
      rotateReset: 'Atur ulang',
      subgroupsHeading: 'Subgrup yang dibangkitkan oleh setiap elemen',
      autoShift: 'Geser subgrup siklik secara otomatis',
      autoShiftTitle: 'Geser subgrup siklik yang dibangkitkan secara otomatis agar sesuai dengan elemen pertama dari atas saat bergerak ke arah maju',
      subLayoutLabel: 'Tata letak',
      subLayoutGrid: 'Kisi',
      subLayoutList: 'Daftar',
      'fact.group': 'Grup',
      'fact.elements': 'Elemen',
      'fact.identity': 'Identitas',
      'fact.operation': 'Operasi',
      opAdd: 'penjumlahan mod {n}',
      opMul: 'perkalian mod {n}',
      'fact.generators': 'Pembangkit',
      'fact.structure': 'Struktur',
      factGeneratorsCount: '{count} dari {order}',
      factGeneratorsNone: '0 (tidak siklik)',
      'hint.notCyclic': 'Tidak ada elemen yang mencapai semua elemen lain: panah dari 1 selalu kembali sebelum cincin penuh.',
      'hint.noLabels': 'Elemen terlalu kecil untuk label bilangan di sini; polanya tetap terlihat.',
      'hint.multiplicative': 'Elemennya adalah bilangan di bawah {n} yang tidak memiliki faktor persekutuan dengannya. Melangkah berarti mengalikan dengan {g} mod {n}.',
      'hint.additive': 'Melangkah berarti menambahkan {g} mod {n}.',
      'hint.mirror': 'Invers saling mencerminkan di seberang sumbu putus-putus yang melalui identitas; elemen pada sumbu adalah inversnya sendiri.',
      'hint.mirrorOffSorted': 'Elemen diurutkan menurut nilai, sehingga invers tidak saling mencerminkan di sini.',
      'hint.mirrorOff': 'Pada urutan ini elemen diurutkan menurut nilai, sehingga invers tidak saling mencerminkan. Aktifkan “Susun elemen menurut pangkat pembangkit” untuk melihatnya saling mencerminkan di seberang sumbu yang melalui identitas.',
      legendHeading: 'Kunci warna: kardinalitas subgrup',
      legendOrder: 'Kardinalitas subgrup: {order}',
      legendSubgroups: { other: '{count} subgrup' },
      legendHeadingInverse: 'Kunci warna: pasangan invers',
      legendSelfInverse: 'invers sendiri: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · elemen {h} berorde {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, sehingga ada {n} / {size} = {count} koset',
      ringFootnote: 'Identitas, {id}, dilingkari.',
      ringFootnoteOrders: 'Identitas, {id}, dilingkari; angka kecil di luar adalah orde setiap elemen.',
      svgAriaLabel: 'Diagram kalung dari {group}',
      'notice.heading': '{group} tidak memiliki pembangkit, sehingga tidak ada langkah yang mencapai setiap elemen',
      'notice.body': 'Grup ini memiliki {count} elemen, tetapi tidak ada satu elemen pun yang mencapai semuanya: jalur terpanjang dari 1 memerlukan {longest} langkah. Grup ini dibangun dari grup siklik {factors}.',
      'notice.whyPowerOfTwo': 'Alasan: n = {n} adalah pangkat dari 2 di atas 4.',
      'notice.whyFourAndOdd': 'Alasan: n = {n} habis dibagi 4 dan oleh sebuah bilangan prima ganjil.',
      'notice.whyTwoOddPrimes': 'Alasan: n = {n} memiliki dua faktor prima ganjil yang berbeda.',
      'notice.rule': '(Z/n)* siklik tepat ketika n adalah 1, 2 atau 4, pangkat bilangan prima ganjil p^k, atau dua kali pangkat itu, 2p^k. Z/n aditif selalu siklik.',
      exportPng: 'Unduh PNG cincin',
      exportSaved: '{filename} disimpan.',
      exportFailed: 'Gambar tidak dapat diekspor di peramban ini.'
    }
});
NT.i18n.register('site', {
    id: {
      'nav.cyclicGroups': 'Grup Siklik'
    }
});
NT.i18n.register('hub', {
    id: {
      'card.cyclicGroups.title': 'Kalung Grup Siklik',
      'card.cyclicGroups.desc': 'Setiap elemen sebuah grup menjadi manik pada sebuah cincin; melangkahlah dengan pembangkit dan tali busur menggambar bintang yang menyentuh setiap manik — dan ketika tidak ada satu elemen pun yang bisa menjangkau semuanya, grup terpecah menjadi cincin-cincin lebih kecil yang menyusunnya.'
    }
});
