/* 261009-tgw fragment: it (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    it: {
      title: 'Gruppi ciclici — Visualizzatore a collana',
      eyebrow: 'teoria dei gruppi · generatori e orbite',
      heading: 'Collana del gruppo ciclico',
      lede: 'Scegli un gruppo. Ogni elemento si dispone su un cerchio, a distanze uguali. Procedere con il generatore traccia le corde, e un generatore che raggiunge ogni elemento è ciò che rende ciclico il gruppo. I gruppi privi di un tale elemento si scompongono nei cerchi da cui sono costruiti.',
      xref: 'Guarda la tavola completa dell’operazione di questo gruppo nella Tavola di Cayley →',
      tablistLabel: 'Operazione di gruppo',
      groupHeading: 'Gruppo',
      subgroupHeading: 'Sottogruppo',
      identityOnly: 'L’elemento neutro produce soltanto se stesso',
      nLabel: 'n — modulo',
      genLabel: 'Sottogruppo visualizzato',
      nNoteClamped: 'n va da 2 a 100, quindi il diagramma mostra n = {n}.',
      layersHeading: 'Livelli',
      extraOptions: 'Mostra opzioni aggiuntive',
      layerCord: 'Mostra il poligono corrispondente',
      layerGuide: 'Mostra il cerchio che collega gli elementi',
      layerElement: 'Percorso di andata',
      layerElementTitle: 'Fare un passo significa combinare l’elemento corrente con {g}',
      layerBackward: 'Disattiva il percorso di ritorno',
      layerPaths: 'Percorsi del sottogruppo',
      resizeTitle: 'Trascina per ridimensionare; fai doppio clic per reimpostare',
      dirLabel: 'Direzione di andata',
      dirCw: 'Senso orario',
      dirCcw: 'Senso antiorario',
      sideInside: 'Dentro',
      sideOutside: 'Fuori',
      colorElement: 'Colore della freccia dell’elemento',
      colorInverse: 'Colore della freccia dell’inverso',
      colorReset: 'Reimposta i colori delle frecce',
      genTop: 'Ruota il generatore selezionato in alto',
      swapColors: 'Scambia i colori dei percorsi di andata e di ritorno',
      customColors: 'Scegli manualmente i colori delle frecce',
      layerColors: 'Colori degli elementi',
      colorByLabel: 'Colora gli elementi in base a',
      colorByOrder: 'Cardinalità del sottogruppo',
      colorByInverse: 'Coppie di inversi',
      layerOrders: 'Etichette dell’ordine',
      layerBygen: 'Disponi gli elementi per potenze del generatore',
      combineForward: 'Percorso di andata, combinando gli elementi con l’elemento selezionato {h}',
      combineBackward: 'Percorso di ritorno, combinando gli elementi con l’inverso dell’elemento selezionato, che è {hinv}',
      combineSelfInverse: '{h} è il proprio inverso, quindi i due percorsi coincidono e sono tracciati una volta sola con una miscela dei due colori',
      factsHeading: 'Questo gruppo',
      cosetButton: 'Esplora le classi laterali',
      cosetHide: 'Smetti di esplorare le classi laterali',
      cosetNoneGenerator: 'Nessuna classe laterale da esplorare; {g} è un generatore',
      cosetProgress: 'Evidenziata ora la classe laterale {i} di {count}',
      autoRotate: 'Rotazione automatica',
      autoRotateOff: 'Disattivata',
      autoRotateCcw: 'Senso antiorario',
      autoRotateCw: 'Senso orario',
      rotateLabel: 'Rotazione — trascina il cerchio',
      rotateBack: 'Ruota di un elemento in senso antiorario',
      rotateForward: 'Ruota di un elemento in senso orario',
      rotateValue: 'Rotazione in passi',
      rotateReset: 'Reimposta',
      subgroupsHeading: 'Sottogruppo generato da ogni elemento',
      autoShift: 'Sposta automaticamente i sottogruppi ciclici',
      autoShiftTitle: 'Sposta automaticamente il sottogruppo ciclico generato in modo che corrisponda al primo elemento dall’alto procedendo nella direzione di andata',
      subLayoutLabel: 'Disposizione',
      subLayoutGrid: 'Griglia',
      subLayoutList: 'Elenco',
      'fact.group': 'Gruppo',
      'fact.elements': 'Elementi',
      'fact.identity': 'Elemento neutro',
      'fact.operation': 'Operazione',
      opAdd: 'addizione modulo {n}',
      opMul: 'moltiplicazione modulo {n}',
      'fact.generators': 'Generatori',
      'fact.structure': 'Struttura',
      factGeneratorsCount: '{count} su {order}',
      factGeneratorsNone: '0 (non ciclico)',
      'hint.notCyclic': 'Nessun elemento raggiunge tutti gli altri: le frecce che partono da 1 tornano sempre indietro prima che il cerchio sia pieno.',
      'hint.noLabels': 'Qui gli elementi sono troppo piccoli per le etichette numeriche; il disegno resta comunque visibile.',
      'hint.multiplicative': 'Gli elementi sono i numeri minori di {n} che non hanno fattori in comune con esso. Procedere significa moltiplicare per {g} modulo {n}.',
      'hint.additive': 'Procedere significa sommare {g} modulo {n}.',
      'hint.mirror': 'Gli inversi si specchiano a vicenda rispetto all’asse tratteggiato che passa per l’elemento neutro; l’elemento sull’asse è il proprio inverso.',
      'hint.mirrorOffSorted': 'Gli elementi sono ordinati per valore, quindi qui gli inversi non si specchiano.',
      'hint.mirrorOff': 'Con questa disposizione gli elementi sono ordinati per valore, quindi gli inversi non si specchiano. Attiva «Disponi gli elementi per potenze del generatore» per vederli specchiarsi rispetto all’asse che passa per l’elemento neutro.',
      legendHeading: 'Legenda dei colori: cardinalità del sottogruppo',
      legendOrder: 'Cardinalità del sottogruppo: {order}',
      legendSubgroups: { one: '{count} sottogruppo', other: '{count} sottogruppi' },
      legendHeadingInverse: 'Legenda dei colori: coppie di inversi',
      legendSelfInverse: 'proprio inverso: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · elemento {h} di ordine {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, quindi ci sono {n} / {size} = {count} classi laterali',
      ringFootnote: 'L’elemento neutro, {id}, è cerchiato.',
      ringFootnoteOrders: 'L’elemento neutro, {id}, è cerchiato; il piccolo numero esterno è l’ordine di ogni elemento.',
      svgAriaLabel: 'Diagramma a collana di {group}',
      'notice.heading': '{group} non ha generatori, quindi nessun percorso raggiunge tutti gli elementi',
      'notice.body': 'Il gruppo ha {count} elementi, ma nessun elemento da solo li raggiunge tutti: il percorso più lungo a partire da 1 compie {longest} passi. Il gruppo è costruito a partire dai gruppi ciclici {factors}.',
      'notice.whyPowerOfTwo': 'Perché: n = {n} è una potenza di 2 maggiore di 4.',
      'notice.whyFourAndOdd': 'Perché: n = {n} è divisibile per 4 e per un primo dispari.',
      'notice.whyTwoOddPrimes': 'Perché: n = {n} ha due fattori primi dispari distinti.',
      'notice.rule': '(Z/n)* è ciclico esattamente quando n è 1, 2 o 4, una potenza p^k di un primo dispari, o il doppio di una di esse, 2p^k. Il gruppo additivo Z/n è sempre ciclico.',
      exportPng: 'Scarica PNG del cerchio',
      exportSaved: 'Salvato: {filename}.',
      exportFailed: 'Non è stato possibile esportare l’immagine in questo browser.'
    }
});
NT.i18n.register('site', {
    it: {
      'nav.cyclicGroups': 'Gruppi ciclici'
    }
});
NT.i18n.register('hub', {
    it: {
      'card.cyclicGroups.title': 'Collana del gruppo ciclico',
      'card.cyclicGroups.desc': 'Ogni elemento di un gruppo diventa una perla su un cerchio; procedi con un generatore e le corde tracciano una stella che tocca ogni perla — e quando nessun elemento da solo può raggiungerle tutte, il gruppo si scompone nei cerchi più piccoli da cui è costruito.'
    }
});
