/* 261009-tgw fragment: ja (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    ja: {
      title: '巡回群：ネックレスビジュアライザー',
      eyebrow: '群論・生成元と軌道',
      heading: '巡回群のネックレス',
      lede: '群を選んでください。すべての要素が、等間隔で円環の上に並びます。生成元の分だけ歩くと弦が描かれ、すべての要素に届く生成元があることが、その群を巡回群にしています。そのような要素のない群は、それを構成する円環に分けられます。',
      xref: 'この群の演算表全体をケイリー表で見る →',
      tablistLabel: '群の演算',
      groupHeading: '群',
      subgroupHeading: '部分群',
      identityOnly: '単位元は自分自身だけを生成します',
      nLabel: 'n：法',
      genLabel: '表示する部分群',
      nNoteClamped: 'nは2から100までなので、図にはn = {n}を表示しています。',
      layersHeading: 'レイヤー',
      extraOptions: 'その他のオプションを表示',
      layerCord: '対応する多角形を表示',
      layerGuide: '結ぶ円を表示',
      layerElement: '前進の経路',
      layerElementTitle: '一歩進むとは、現在の要素を{g}と合成することです',
      layerBackward: '後退の経路を無効にする',
      layerPaths: '部分群の経路',
      resizeTitle: 'ドラッグでサイズ変更、ダブルクリックでリセット',
      dirLabel: '前進の向き',
      dirCw: '時計回り',
      dirCcw: '反時計回り',
      sideInside: '内側',
      sideOutside: '外側',
      colorElement: '要素の矢印の色',
      colorInverse: '逆元の矢印の色',
      colorReset: '矢印の色をリセット',
      genTop: '選択した生成元を真上に回転',
      swapColors: '前進の経路と後退の経路の色を入れ替える',
      customColors: '矢印の色を手動で選ぶ',
      layerColors: '要素の色',
      colorByLabel: '要素の色分け',
      colorByOrder: '部分群の要素数',
      colorByInverse: '逆元のペア',
      layerOrders: '位数ラベル',
      layerBygen: '生成元のべき乗の順に要素を並べる',
      combineForward: '前進の経路。選択した要素{h}と各要素を合成します',
      combineBackward: '後退の経路。選択した要素の逆元である{hinv}と各要素を合成します',
      combineSelfInverse: '{h}は自分自身が逆元なので、二つの歩みは同じ一つのものになり、二色を混ぜた色で一度だけ描かれます',
      factsHeading: 'この群について',
      cosetButton: '剰余類を調べる',
      cosetHide: '剰余類を調べるのをやめる',
      cosetNoneGenerator: '調べる剰余類はありません。{g}は生成元です',
      cosetProgress: '現在、{count}個中{i}番目の剰余類を強調表示しています',
      autoRotate: '自動回転',
      autoRotateOff: 'オフ',
      autoRotateCcw: '反時計回り',
      autoRotateCw: '時計回り',
      rotateLabel: '回転：輪をドラッグ',
      rotateBack: '要素一つ分だけ反時計回りに回転',
      rotateForward: '要素一つ分だけ時計回りに回転',
      rotateValue: '回転ステップ数',
      rotateReset: 'リセット',
      subgroupsHeading: '各要素が生成する部分群',
      autoShift: '巡回部分群を自動でずらす',
      autoShiftTitle: '前進の向きに進んだとき、生成された巡回部分群を、上から数えて最初の要素に合うよう自動でずらします',
      subLayoutLabel: 'レイアウト',
      subLayoutGrid: 'グリッド',
      subLayoutList: 'リスト',
      'fact.group': '群',
      'fact.elements': '要素',
      'fact.identity': '単位元',
      'fact.operation': '演算',
      opAdd: '法{n}での加法',
      opMul: '法{n}での乗法',
      'fact.generators': '生成元',
      'fact.structure': '構造',
      factGeneratorsCount: '{order}個中{count}個',
      factGeneratorsNone: '0（巡回群ではない）',
      'hint.notCyclic': 'ほかのすべての要素へ順にたどり着ける要素はありません。1から出た矢印は、輪が埋まる前に必ず戻ってきます。',
      'hint.noLabels': 'ここでは要素が小さすぎて数のラベルを表示できませんが、模様は見えます。',
      'hint.multiplicative': '要素は、{n}より小さく{n}と共通の因数を持たない数です。一歩進むとは、{g}を掛けて{n}を法とすることです。',
      'hint.additive': '一歩進むとは、{g}を足して{n}を法とすることです。',
      'hint.mirror': '逆元どうしは、単位元を通る破線の軸をはさんで互いに鏡像になります。軸上にある要素は自分自身が逆元です。',
      'hint.mirrorOffSorted': '要素は値の順に並んでいるため、ここでは逆元は鏡像になりません。',
      'hint.mirrorOff': 'この並びでは要素が値の順になっているため、逆元は鏡像になりません。「生成元のべき乗の順に要素を並べる」をオンにすると、単位元を通る軸をはさんで鏡像になる様子が見られます。',
      legendHeading: '色の凡例：部分群の要素数',
      legendOrder: '部分群の要素数：{order}',
      legendSubgroups: { other: '{count}個の部分群' },
      legendHeadingInverse: '色の凡例：逆元のペア',
      legendSelfInverse: '自分自身が逆元：{list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · 要素{h}、位数{k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}なので、剰余類は{n} / {size} = {count}個あります',
      ringFootnote: '単位元{id}は丸で囲まれています。',
      ringFootnoteOrders: '単位元{id}は丸で囲まれています。外側の小さな数は各要素の位数です。',
      svgAriaLabel: '{group}のネックレス図',
      'notice.heading': '{group}には生成元がないため、すべての要素に届く歩みはありません',
      'notice.body': 'この群には{count}個の要素がありますが、すべてに届く要素は一つもありません。1から出る最長の歩みは{longest}ステップです。この群は巡回群{factors}から構成されています。',
      'notice.whyPowerOfTwo': '理由：n = {n}は4より大きい2のべきです。',
      'notice.whyFourAndOdd': '理由：n = {n}は4でも、ある奇素数でも割り切れます。',
      'notice.whyTwoOddPrimes': '理由：n = {n}は異なる二つの奇素因数を持ちます。',
      'notice.rule': '(Z/n)*が巡回群になるのは、nが1、2、4、奇素数のべきp^k、またはそれを倍にした2p^kであるときに限ります。加法群Z/nは常に巡回群です。',
      exportPng: 'リングのPNGをダウンロード',
      exportSaved: '{filename}を保存しました。',
      exportFailed: 'このブラウザーでは画像をエクスポートできませんでした。'
    }
});
NT.i18n.register('site', {
    ja: {
      'nav.cyclicGroups': '巡回群'
    }
});
NT.i18n.register('hub', {
    ja: {
      'card.cyclicGroups.title': '巡回群のネックレス',
      'card.cyclicGroups.desc': '群のすべての要素が円環の上のビーズになります。生成元ずつ進むと、弦がすべてのビーズに触れる星形を描きます。そして、どの一つの要素でもすべてに届かないとき、群はそれを構成するより小さな円環に分かれます。'
    }
});
