/* 261009-tgw fragment: ko (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    ko: {
      title: '순환군 — 목걸이 시각화 도구',
      eyebrow: '군론 · 생성원과 궤도',
      heading: '순환군 목걸이',
      lede: '군을 하나 고르세요. 모든 원소가 같은 간격으로 고리 위에 놓입니다. 생성원만큼 걸어가면 현이 그려지고, 모든 원소에 이르는 생성원이 있다는 것이 그 군을 순환군으로 만듭니다. 그런 원소가 없는 군은 그 군을 이루는 고리들로 나뉩니다.',
      xref: '이 군의 전체 연산표를 케일리 표에서 보기 →',
      tablistLabel: '군 연산',
      groupHeading: '군',
      subgroupHeading: '부분군',
      identityOnly: '항등원은 자기 자신만 생성합니다',
      nLabel: 'n — 법',
      genLabel: '시각화할 부분군',
      nNoteClamped: 'n의 범위는 2부터 100까지이므로 도표의 값은 n = {n}입니다.',
      layersHeading: '레이어',
      extraOptions: '추가 옵션 표시',
      layerCord: '대응하는 다각형 표시',
      layerGuide: '연결 원 표시',
      layerElement: '정방향 경로',
      layerElementTitle: '한 걸음은 현재 원소와 {g}의 결합입니다',
      layerBackward: '역방향 경로 비활성화',
      layerPaths: '부분군 경로',
      resizeTitle: '끌어서 크기를 조절하고, 두 번 클릭하면 초기화됩니다',
      dirLabel: '정방향 진행 방향',
      dirCw: '시계 방향',
      dirCcw: '시계 반대 방향',
      sideInside: '안쪽',
      sideOutside: '바깥쪽',
      colorElement: '원소 화살표 색',
      colorInverse: '역원 화살표 색',
      colorReset: '화살표 색 초기화',
      genTop: '선택한 생성원을 맨 위로 회전',
      swapColors: '정방향 경로와 역방향 경로의 색 바꾸기',
      customColors: '화살표 색을 직접 선택',
      layerColors: '원소 색',
      colorByLabel: '원소 색 구분 기준',
      colorByOrder: '부분군의 원소 수',
      colorByInverse: '역원 쌍',
      layerOrders: '위수 라벨',
      layerBygen: '생성원의 거듭제곱 순서로 원소 배열',
      combineForward: '정방향 경로. 결합에 쓰는 원소는 선택한 원소 {h}입니다',
      combineBackward: '역방향 경로. 결합에 쓰는 원소는 선택한 원소의 역원인 {hinv}입니다',
      combineSelfInverse: '{h}의 역원은 자기 자신이므로 두 경로는 하나로 같고, 두 색을 섞은 색으로 한 번만 그려집니다',
      factsHeading: '이 군',
      cosetButton: '잉여류 탐색',
      cosetHide: '잉여류 탐색 중지',
      cosetNoneGenerator: '탐색할 잉여류가 없습니다 (생성원: {g})',
      cosetProgress: '현재 잉여류 {count}개 중 {i}번째를 강조하고 있습니다',
      autoRotate: '자동 회전',
      autoRotateOff: '끔',
      autoRotateCcw: '시계 반대 방향',
      autoRotateCw: '시계 방향',
      rotateLabel: '회전 — 고리를 끌어 보세요',
      rotateBack: '원소 하나만큼 시계 반대 방향으로 회전',
      rotateForward: '원소 하나만큼 시계 방향으로 회전',
      rotateValue: '회전 단계 수',
      rotateReset: '초기화',
      subgroupsHeading: '각 원소가 생성하는 부분군',
      autoShift: '순환 부분군 자동 이동',
      autoShiftTitle: '정방향으로 나아갈 때, 생성된 순환 부분군을 위에서부터 첫 번째 원소에 맞도록 자동으로 이동합니다',
      subLayoutLabel: '배치',
      subLayoutGrid: '격자',
      subLayoutList: '목록',
      'fact.group': '군',
      'fact.elements': '원소',
      'fact.identity': '항등원',
      'fact.operation': '연산',
      opAdd: '법 {n}에 대한 덧셈',
      opMul: '법 {n}에 대한 곱셈',
      'fact.generators': '생성원',
      'fact.structure': '구조',
      factGeneratorsCount: '{order}개 중 {count}개',
      factGeneratorsNone: '0 (순환군 아님)',
      'hint.notCyclic': '다른 모든 원소에 차례로 이르는 원소는 없습니다. 1에서 나가는 화살표는 고리가 다 채워지기 전에 항상 되돌아옵니다.',
      'hint.noLabels': '여기서는 원소가 너무 작아 숫자 라벨을 표시할 수 없지만, 무늬는 그대로 보입니다.',
      'hint.multiplicative': '원소는 {n}보다 작으면서 {n}의 인수를 공유하지 않는 수입니다. 한 걸음 나아가는 것은 법 {n}에서 {g}만큼 곱하는 것입니다.',
      'hint.additive': '한 걸음 나아가는 것은 법 {n}에서 {g}만큼 더하는 것입니다.',
      'hint.mirror': '역원끼리는 항등원을 지나는 점선 축을 기준으로 서로 거울상을 이룹니다. 축 위에 있는 원소는 자기 자신이 역원입니다.',
      'hint.mirrorOffSorted': '원소가 값 순서로 정렬되어 있어, 여기서는 역원이 거울상을 이루지 않습니다.',
      'hint.mirrorOff': '이 순서에서는 원소가 값 순서로 정렬되어 있어 역원이 거울상을 이루지 않습니다. “생성원의 거듭제곱 순서로 원소 배열”을 켜면, 항등원을 지나는 축을 기준으로 거울상을 이루는 모습을 볼 수 있습니다.',
      legendHeading: '색 범례: 부분군의 원소 수',
      legendOrder: '부분군의 원소 수: {order}',
      legendSubgroups: { other: '부분군 {count}개' },
      legendHeadingInverse: '색 범례: 역원 쌍',
      legendSelfInverse: '자기 자신이 역원: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · 원소 {h}, 위수 {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, 따라서 잉여류는 {n} / {size} = {count}개입니다',
      ringFootnote: '항등원 {id}에 동그라미가 쳐져 있습니다.',
      ringFootnoteOrders: '항등원 {id}에 동그라미가 쳐져 있고, 바깥쪽의 작은 숫자는 각 원소의 위수입니다.',
      svgAriaLabel: '{group}의 목걸이 도표',
      'notice.heading': '{group}에는 생성원이 없으므로 모든 원소에 이르는 경로가 없습니다',
      'notice.body': '이 군에는 원소가 {count}개 있지만, 모든 원소에 이르는 원소는 하나도 없습니다. 1에서 출발하는 가장 긴 경로는 {longest}걸음입니다. 이 군을 이루는 순환군은 {factors}입니다.',
      'notice.whyPowerOfTwo': '이유: n = {n}. 이 값은 4보다 큰 2의 거듭제곱입니다.',
      'notice.whyFourAndOdd': '이유: n = {n}. 이 값은 4로도, 어떤 홀수 소수로도 나누어떨어집니다.',
      'notice.whyTwoOddPrimes': '이유: n = {n}. 이 값은 서로 다른 홀수 소인수를 두 개 가집니다.',
      'notice.rule': '(Z/n)*의 순환 여부: n이 1, 2, 4, 홀수 소수의 거듭제곱 p^k, 또는 그 배인 2p^k일 때만 순환군입니다. 덧셈군 Z/n은 항상 순환군입니다.',
      exportPng: '고리 PNG 다운로드',
      exportSaved: '{filename} 파일을 저장했습니다.',
      exportFailed: '이 브라우저에서는 그림을 내보낼 수 없었습니다.'
    }
});
NT.i18n.register('site', {
    ko: {
      'nav.cyclicGroups': '순환군'
    }
});
NT.i18n.register('hub', {
    ko: {
      'card.cyclicGroups.title': '순환군 목걸이',
      'card.cyclicGroups.desc': '군의 모든 원소가 고리 위의 구슬이 됩니다. 생성원만큼 나아가면 현이 모든 구슬에 닿는 별 모양을 그리고, 어떤 원소 하나로도 모든 구슬에 이를 수 없으면 군은 그 군을 이루는 더 작은 고리들로 나뉩니다.'
    }
});
