/* 261009-tgw fragment: ku (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    ku: {
      title: 'Grûpên çerxî — Dîmenkera gerdanê',
      eyebrow: 'teoriya grûpan · çêker û dewrgeh',
      heading: 'Gerdana grûpa çerxî',
      lede: 'Grûpekê hilbijêre. Her hêman bi dûrahiyên wekhev li ser xelekekê cih digire. Gerîna bi çêker watar dikişîne, û çêkerek ku digihîje her hêmanê grûpê çerxî dike. Grûpên ku hêmaneke weha tê de tune ye li xelekên ku ji wan hatine avakirin tên parçekirin.',
      xref: 'Tabloya operasyonê ya tevahî ya vê grûpê di Tabloya Cayley de bibîne →',
      tablistLabel: 'Operasyona grûpê',
      groupHeading: 'Grûp',
      subgroupHeading: 'Binegrûp',
      identityOnly: 'Hêmana bêalî tenê xwe çêdike',
      nLabel: 'n — modul',
      genLabel: 'Binegrûpa tê nîşandan',
      nNoteClamped: 'n ji 2 heta 100 diçe, ji ber vê diyagram n = {n} nîşan dide.',
      layersHeading: 'Qat',
      extraOptions: 'Vebijarkên zêde nîşan bide',
      layerCord: 'Pirgoşeya têkildar nîşan bide',
      layerGuide: 'Çembera girêdanê nîşan bide',
      layerElement: 'Rêya pêş',
      layerElementTitle: 'Gav avêtin tê wateya tevlihevkirina hêmana heyî bi {g} re',
      layerBackward: 'Rêya paş neçalak bike',
      layerPaths: 'Rêyên binegrûpê',
      resizeTitle: 'Ji bo guherandina mezinahiyê bikişîne; ji bo vegerandinê du caran bitikîne',
      dirLabel: 'Aliyê pêş',
      dirCw: 'Bi aliyê saetê',
      dirCcw: 'Berevajî aliyê saetê',
      sideInside: 'Hundir',
      sideOutside: 'Derve',
      colorElement: 'Rengê tîra hêmanê',
      colorInverse: 'Rengê tîra berevajî',
      colorReset: 'Rengên tîran ji nû ve',
      genTop: 'Çêkera hilbijartî bizivirîne jorê',
      swapColors: 'Rengên rêya pêş û rêya paş biguherîne',
      customColors: 'Rengên tîran bi destan hilbijêre',
      layerColors: 'Rengên hêmanan',
      colorByLabel: 'Hêmanan rengîn bike li gorî',
      colorByOrder: 'Hejmara hêmanên binegrûpê',
      colorByInverse: 'Cotên berevajî',
      layerOrders: 'Etîketên rêzê',
      layerBygen: 'Hêmanan li gorî hêzên çêker rêz bike',
      combineForward: 'Rêya pêş, bi tevlihevkirina hêmanan bi hêmana hilbijartî {h} re',
      combineBackward: 'Rêya paş, bi tevlihevkirina hêmanan bi berevajiya hêmana hilbijartî re, ku {hinv} e',
      combineSelfInverse: '{h} berevajiya xwe ye, ji ber vê her du gerîn yek in û tenê carekê bi tevliheviyek ji her du rengan têne xêzkirin',
      factsHeading: 'Ev grûp',
      cosetButton: 'Hevkoman vekole',
      cosetHide: 'Vekolîna hevkoman rawestîne',
      cosetNoneGenerator: 'Hevkomek tune ye ku were vekolîn; {g} çêker e',
      cosetProgress: 'Niha hevkoma {i} ji {count} tê ronîkirin',
      autoRotate: 'Zivirîna bixwe',
      autoRotateOff: 'Girtî',
      autoRotateCcw: 'Berevajî aliyê saetê',
      autoRotateCw: 'Bi aliyê saetê',
      rotateLabel: 'Zivirîn — xelekê bikişîne',
      rotateBack: 'Hêmanekê berevajî aliyê saetê bizivirîne',
      rotateForward: 'Hêmanekê bi aliyê saetê bizivirîne',
      rotateValue: 'Zivirîn bi gavan',
      rotateReset: 'Ji nû ve',
      subgroupsHeading: 'Binegrûpa ku her hêman çêdike',
      autoShift: 'Binegrûpên çerxî bixwe bilivîne',
      autoShiftTitle: 'Binegrûpa çerxî ya hatî çêkirin bixwe bilivîne da ku bi hêmana yekem ji jor re bi hev bikeve dema ku li aliyê pêş diçî',
      subLayoutLabel: 'Rêzkirin',
      subLayoutGrid: 'Tor',
      subLayoutList: 'Lîste',
      'fact.group': 'Grûp',
      'fact.elements': 'Hêman',
      'fact.identity': 'Hêmana bêalî',
      'fact.operation': 'Operasyon',
      opAdd: 'lêzêdekirin mod {n}',
      opMul: 'lêkdan mod {n}',
      'fact.generators': 'Çêker',
      'fact.structure': 'Avahî',
      factGeneratorsCount: '{count} ji {order}',
      factGeneratorsNone: '0 (ne çerxî ye)',
      'hint.notCyclic': 'Tu hêman bi gerînê nagihîje hemû hêmanên din: tîrên ji 1 berî tijîbûna xelekê vedigerin.',
      'hint.noLabels': 'Hêman ji bo etîketên hejmaran li vir pir biçûk in; şablon hîn jî tê dîtin.',
      'hint.multiplicative': 'Hêman ew hejmarên ji {n} biçûktir in ku bi wî re tu faktora hevpar tune. Gav avêtin tê wateya lêkdana bi {g} mod {n}.',
      'hint.additive': 'Gav avêtin tê wateya lêzêdekirina {g} mod {n}.',
      'hint.mirror': 'Berevajî li ser eksa xêza qutkirî ya di hêmana bêalî re derbas dibe neynikên hev in; hêmana li ser eksê berevajiya xwe ye.',
      'hint.mirrorOffSorted': 'Hêman li gorî nirxê hatine rêzkirin, ji ber vê berevajî li vir neynikên hev nînin.',
      'hint.mirrorOff': 'Di vê rêzê de hêman li gorî nirxê hatine rêzkirin, ji ber vê berevajî neynikên hev nînin. Vebijarka «Hêmanan li gorî hêzên çêker rêz bike» vekirî bike da ku bibînî ka çawa li ser eksa di hêmana bêalî re derbas dibe neynikên hev dibin.',
      legendHeading: 'Mifteya rengan: hejmara hêmanên binegrûpê',
      legendOrder: 'Hejmara hêmanên binegrûpê: {order}',
      legendSubgroups: { one: '{count} binegrûp', other: '{count} binegrûp' },
      legendHeadingInverse: 'Mifteya rengan: cotên berevajî',
      legendSelfInverse: 'berevajiya xwe: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · hêmana {h} ya bi rêza {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, ji ber vê {n} / {size} = {count} hevkom hene',
      ringFootnote: 'Hêmana bêalî, {id}, bi xelekekê hatiye dorpêçkirin.',
      ringFootnoteOrders: 'Hêmana bêalî, {id}, bi xelekekê hatiye dorpêçkirin; hejmara biçûk a derve rêza her hêmanê ye.',
      svgAriaLabel: 'Diyagrama gerdanê ya {group}',
      'notice.heading': 'Ji bo {group} çêker tune ye, ji ber vê tu gerîn nagihîje her hêmanê',
      'notice.body': 'Grûp {count} hêmanan dihewîne, lê tu hêmanek yekane nagihîje hemûyan: dirêjtirîn gerîna ji 1 dest pê dike {longest} gavan digire. Grûp ji grûpên çerxî {factors} hatiye avakirin.',
      'notice.whyPowerOfTwo': 'Sedem: n = {n} hêzeke 2 ye ku ji 4 mezintir e.',
      'notice.whyFourAndOdd': 'Sedem: n = {n} bi 4 û bi hejmareke seretayî ya tak dabeş dibe.',
      'notice.whyTwoOddPrimes': 'Sedem: n = {n} du faktorên seretayî yên tak û ji hev cuda hene.',
      'notice.rule': '(Z/n)* tam wê demê çerxî ye ku n yek ji 1, 2 an 4 be, hêzeke hejmareke seretayî ya tak p^k, an du caran ya wê, 2p^k. Grûpa lêzêdekirinê Z/n her dem çerxî ye.',
      exportPng: 'PNG ya xelekê dakêşe',
      exportSaved: '{filename} hate tomarkirin.',
      exportFailed: 'Wêne di vê gerokê de nehat derxistin.'
    }
});
NT.i18n.register('site', {
    ku: {
      'nav.cyclicGroups': 'Grûpên çerxî'
    }
});
NT.i18n.register('hub', {
    ku: {
      'card.cyclicGroups.title': 'Gerdana grûpa çerxî',
      'card.cyclicGroups.desc': 'Her hêmana grûpekê dibe mircanek li ser xelekekê; bi çêkerekê gavan bavêje û watar stêrkekê dikişînin ku destê xwe dide her mircanê — û dema tu hêmanek yekane nikaribe bigihîje hemûyan, grûp li xelekên biçûktir ên ku jê hatine avakirin tê parçekirin.'
    }
});
