/* 261009-tgw fragment: la (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    la: {
      title: 'Greges cyclici — Visualizator monilis',
      eyebrow: 'theoria gregum · generatores et orbitae',
      heading: 'Monile gregis cyclici',
      lede: 'Elige gregem. Quodque elementum in anulo sedet, aequis intervallis dispositum. Si per generatorem progrederis, chordae ducuntur, et generator qui ad omnia elementa pervenit gregem cyclicum facit. Greges sine tali elemento in anulos ex quibus constructi sunt dividuntur.',
      xref: 'Vide totam tabulam operationis huius gregis in Tabula Cayleiana →',
      tablistLabel: 'Operatio gregis',
      groupHeading: 'Grex',
      subgroupHeading: 'Subgrex',
      identityOnly: 'Elementum neutrum se solum generat',
      nLabel: 'n — modulus',
      genLabel: 'Subgrex depictus',
      nNoteClamped: 'n a 2 ad 100 currit, itaque diagramma n = {n} ostendit.',
      layersHeading: 'Strata',
      extraOptions: 'Ostende optiones additas',
      layerCord: 'Ostende polygonum respondens',
      layerGuide: 'Ostende circulum connectentem',
      layerElement: 'Via prorsum',
      layerElementTitle: 'Gradum facere est elementum praesens cum {g} componere',
      layerBackward: 'Exstingue viam retro',
      layerPaths: 'Viae subgregis',
      resizeTitle: 'Trahe ut magnitudinem mutes; bis preme ut restituas',
      dirLabel: 'Directio prorsum',
      dirCw: 'Secundum horologium',
      dirCcw: 'Contra horologium',
      sideInside: 'Intus',
      sideOutside: 'Extra',
      colorElement: 'Color sagittae elementi',
      colorInverse: 'Color sagittae inversi',
      colorReset: 'Restitue colores sagittarum',
      genTop: 'Verte generatorem electum ad summum',
      swapColors: 'Muta colores viae prorsum et viae retro',
      customColors: 'Elige colores sagittarum manu',
      layerColors: 'Colores elementorum',
      colorByLabel: 'Elementa colora secundum',
      colorByOrder: 'Cardinalitas subgregis',
      colorByInverse: 'Paria inversa',
      layerOrders: 'Notae ordinis',
      layerBygen: 'Ordina elementa secundum potestates generatoris',
      combineForward: 'Via prorsum, elementa cum elemento electo {h} componens',
      combineBackward: 'Via retro, elementa cum inverso elementi electi componens, quod est {hinv}',
      combineSelfInverse: '{h} sibi ipsi inversum est, itaque ambae ambulationes una eademque sunt, semel in colore ex duobus mixto ductae',
      factsHeading: 'Hic grex',
      cosetButton: 'Explora classes laterales',
      cosetHide: 'Desine classes laterales explorare',
      cosetNoneGenerator: 'Nullae classes laterales explorandae; {g} generator est',
      cosetProgress: 'Nunc classis lateralis {i} ex {count} illustratur',
      autoRotate: 'Rotatio automatica',
      autoRotateOff: 'Exstinctum',
      autoRotateCcw: 'Contra horologium',
      autoRotateCw: 'Secundum horologium',
      rotateLabel: 'Rotatio — trahe anulum',
      rotateBack: 'Verte unum elementum contra horologium',
      rotateForward: 'Verte unum elementum secundum horologium',
      rotateValue: 'Rotatio per gradus',
      rotateReset: 'Restitue',
      subgroupsHeading: 'Subgrex a quoque elemento generatus',
      autoShift: 'Muta subgreges cyclicos automatice',
      autoShiftTitle: 'Subgregem cyclicum generatum automatice ita muta ut a primo elemento a summo in directione prorsum incipiat',
      subLayoutLabel: 'Species',
      subLayoutGrid: 'Craticula',
      subLayoutList: 'Elenchus',
      'fact.group': 'Grex',
      'fact.elements': 'Elementa',
      'fact.identity': 'Elementum neutrum',
      'fact.operation': 'Operatio',
      opAdd: 'additio mod {n}',
      opMul: 'multiplicatio mod {n}',
      'fact.generators': 'Generatores',
      'fact.structure': 'Structura',
      factGeneratorsCount: '{count} ex {order}',
      factGeneratorsNone: '0 (non cyclicus)',
      'hint.notCyclic': 'Nullum elementum ad omnia cetera elementa pervenit: sagittae ab 1 semper redeunt antequam anulus plenus est.',
      'hint.noLabels': 'Elementa hic nimis parva sunt pro notis numerorum; forma tamen apparet.',
      'hint.multiplicative': 'Elementa sunt numeri minores quam {n} qui nullum factorem cum {n} communem habent. Gradum facere est multiplicare per {g} mod {n}.',
      'hint.additive': 'Gradum facere est addere {g} mod {n}.',
      'hint.mirror': 'Inversa se invicem speculantur trans axem interruptum per elementum neutrum; elementum in axe sibi ipsi inversum est.',
      'hint.mirrorOffSorted': 'Elementa secundum valorem ordinata sunt, itaque inversa hic non speculantur.',
      'hint.mirrorOff': 'Hoc ordine elementa secundum valorem ordinata sunt, itaque inversa non speculantur. Accende «Ordina elementa secundum potestates generatoris» ut ea trans axem per elementum neutrum speculari videas.',
      legendHeading: 'Clavis colorum: cardinalitas subgregis',
      legendOrder: 'Cardinalitas subgregis: {order}',
      legendSubgroups: { one: '{count} subgrex', other: '{count} subgreges' },
      legendHeadingInverse: 'Clavis colorum: paria inversa',
      legendSelfInverse: 'sibi ipsi inversum: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · elementum {h} ordinis {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, itaque sunt {n} / {size} = {count} classes laterales',
      ringFootnote: 'Elementum neutrum, {id}, circumdatum est.',
      ringFootnoteOrders: 'Elementum neutrum, {id}, circumdatum est; parvus numerus exterior est ordo cuiusque elementi.',
      svgAriaLabel: 'Diagramma monilis pro {group}',
      'notice.heading': '{group} generatorem non habet, itaque nulla ambulatio ad omnia elementa pervenit',
      'notice.body': 'Grex {count} elementa habet, sed nullum elementum singulare omnia attingit: longissima ambulatio ab 1 {longest} gradus accipit. Grex ex gregibus cyclicis {factors} constructus est.',
      'notice.whyPowerOfTwo': 'Causa: n = {n} potestas numeri 2 supra 4 est.',
      'notice.whyFourAndOdd': 'Causa: n = {n} per 4 et per numerum primum imparem dividitur.',
      'notice.whyTwoOddPrimes': 'Causa: n = {n} duos factores primos impares diversos habet.',
      'notice.rule': '(Z/n)* cyclicus est si et solum si n est 1, 2 vel 4, potestas p^k numeri primi imparis, vel duplum talis potestatis, 2p^k. Grex additivus Z/n semper cyclicus est.',
      exportPng: 'Deprome PNG anuli',
      exportSaved: 'Servatum est {filename}.',
      exportFailed: 'Imago in hoc navigatro exportari non potuit.'
    }
});
NT.i18n.register('site', {
    la: {
      'nav.cyclicGroups': 'Greges cyclici'
    }
});
NT.i18n.register('hub', {
    la: {
      'card.cyclicGroups.title': 'Monile gregis cyclici',
      'card.cyclicGroups.desc': 'Omne elementum gregis fit gemma in anulo; gradus per generatorem fac et chordae stellam ducunt quae omnem gemmam tangit — et cum nullum elementum singulare ad omnia pervenire potest, grex in minores anulos ex quibus constructus est dividitur.'
    }
});
