/* 261009-tgw fragment: lv (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    lv: {
      title: 'Cikliskās grupas — kaklarotas vizualizētājs',
      eyebrow: 'grupu teorija · ģeneratori un orbītas',
      heading: 'Cikliskās grupas kaklarota',
      lede: 'Izvēlies grupu. Katrs elements atrodas uz apļa, vienādos attālumos. Soļojot ar ģeneratoru, tiek zīmētas hordas, un ģenerators, kas sasniedz katru elementu, padara grupu par ciklisku. Grupas, kurām nav šāda elementa, sadalās apļos, no kuriem tās ir veidotas.',
      xref: 'Šīs grupas pilno darbības tabulu skaties Keilija tabulā →',
      tablistLabel: 'Grupas darbība',
      groupHeading: 'Grupa',
      subgroupHeading: 'Apakšgrupa',
      identityOnly: 'Neitrālais elements rada tikai pats sevi',
      nLabel: 'n — modulis',
      genLabel: 'Attēlotā apakšgrupa',
      nNoteClamped: 'n var būt no 2 līdz 100, tāpēc diagramma rāda n = {n}.',
      layersHeading: 'Slāņi',
      extraOptions: 'Rādīt papildu opcijas',
      layerCord: 'Rādīt atbilstošo daudzstūri',
      layerGuide: 'Rādīt savienojošo apli',
      layerElement: 'Ceļš uz priekšu',
      layerElementTitle: 'Spert soli nozīmē apvienot pašreizējo elementu ar {g}',
      layerBackward: 'Atspējot ceļu atpakaļ',
      layerPaths: 'Apakšgrupas ceļi',
      resizeTitle: 'Velc, lai mainītu izmēru; veic dubultklikšķi, lai atiestatītu',
      dirLabel: 'Virziens uz priekšu',
      dirCw: 'Pulksteņrādītāju kustības virzienā',
      dirCcw: 'Pretēji pulksteņrādītāju kustības virzienam',
      sideInside: 'Iekšpusē',
      sideOutside: 'Ārpusē',
      colorElement: 'Elementa bultu krāsa',
      colorInverse: 'Inversā elementa bultu krāsa',
      colorReset: 'Atiestatīt bultu krāsas',
      genTop: 'Pagriezt izvēlēto ģeneratoru uz augšu',
      swapColors: 'Apmainīt ceļa uz priekšu un atpakaļ krāsas',
      customColors: 'Izvēlēties bultu krāsas manuāli',
      layerColors: 'Elementu krāsas',
      colorByLabel: 'Elementu krāsošana',
      colorByOrder: 'Apakšgrupas kardinalitāte',
      colorByInverse: 'Inverso elementu pāri',
      layerOrders: 'Kārtas iezīmes',
      layerBygen: 'Sakārtot elementus pēc ģeneratora pakāpēm',
      combineForward: 'Ceļš uz priekšu, apvienojot elementus ar izvēlēto elementu {h}',
      combineBackward: 'Ceļš atpakaļ, apvienojot elementus ar izvēlētā elementa inverso, kas ir {hinv}',
      combineSelfInverse: '{h} ir pats sev inverss, tāpēc abas soļošanas ir viena un tā pati, uzzīmēta vienreiz abu krāsu sajaukumā',
      factsHeading: 'Šī grupa',
      cosetButton: 'Pētīt blakusklases',
      cosetHide: 'Beigt pētīt blakusklases',
      cosetNoneGenerator: 'Nav blakusklašu, ko pētīt; {g} ir ģenerators',
      cosetProgress: 'Pašlaik izcelta blakusklase {i} no {count}',
      autoRotate: 'Automātiska griešana',
      autoRotateOff: 'Izslēgta',
      autoRotateCcw: 'Pretēji pulksteņrādītāju kustības virzienam',
      autoRotateCw: 'Pulksteņrādītāju kustības virzienā',
      rotateLabel: 'Pagrieziens — velc apli',
      rotateBack: 'Pagriezt par vienu elementu pretēji pulksteņrādītāju kustības virzienam',
      rotateForward: 'Pagriezt par vienu elementu pulksteņrādītāju kustības virzienā',
      rotateValue: 'Pagrieziens soļos',
      rotateReset: 'Atiestatīt',
      subgroupsHeading: 'Apakšgrupa, ko ģenerē katrs elements',
      autoShift: 'Automātiski pārbīdīt cikliskās apakšgrupas',
      autoShiftTitle: 'Automātiski pārbīdīt ģenerēto ciklisko apakšgrupu, lai tā atbilstu pirmajam elementam no augšas, virzoties uz priekšu',
      subLayoutLabel: 'Izkārtojums',
      subLayoutGrid: 'Režģis',
      subLayoutList: 'Saraksts',
      'fact.group': 'Grupa',
      'fact.elements': 'Elementi',
      'fact.identity': 'Neitrālais elements',
      'fact.operation': 'Darbība',
      opAdd: 'saskaitīšana mod {n}',
      opMul: 'reizināšana mod {n}',
      'fact.generators': 'Ģeneratori',
      'fact.structure': 'Struktūra',
      factGeneratorsCount: '{count} no {order}',
      factGeneratorsNone: '0 (nav cikliska)',
      'hint.notCyclic': 'Neviens elements nenonāk līdz visiem pārējiem: bultas no 1 vienmēr atgriežas, pirms aplis ir pilns.',
      'hint.noLabels': 'Elementi šeit ir pārāk mazi skaitļu iezīmēm; raksts joprojām ir redzams.',
      'hint.multiplicative': 'Elementi ir skaitļi, kas mazāki par {n} un kuriem nav kopīga reizinātāja ar to. Solis nozīmē reizināt ar {g} mod {n}.',
      'hint.additive': 'Solis nozīmē pieskaitīt {g} mod {n}.',
      'hint.mirror': 'Inversie elementi atspoguļo viens otru pa raustīto asi caur neitrālo elementu; elements uz ass ir pats sev inverss.',
      'hint.mirrorOffSorted': 'Elementi ir sakārtoti pēc vērtības, tāpēc inversie elementi šeit neatspoguļojas.',
      'hint.mirrorOff': 'Šādā secībā elementi ir sakārtoti pēc vērtības, tāpēc inversie elementi neatspoguļojas. Ieslēdz „Sakārtot elementus pēc ģeneratora pakāpēm”, lai redzētu, kā tie atspoguļojas pa asi caur neitrālo elementu.',
      legendHeading: 'Krāsu atslēga: apakšgrupas kardinalitāte',
      legendOrder: 'Apakšgrupas kardinalitāte: {order}',
      legendSubgroups: { zero: '{count} apakšgrupu', one: '{count} apakšgrupa', other: '{count} apakšgrupas' },
      legendHeadingInverse: 'Krāsu atslēga: inverso elementu pāri',
      legendSelfInverse: 'pats sev inverss: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · elements {h} ar kārtu {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, tātad blakusklašu skaits ir {n} / {size} = {count}',
      ringFootnote: 'Neitrālais elements, {id}, ir apvilkts ar apli.',
      ringFootnoteOrders: 'Neitrālais elements, {id}, ir apvilkts ar apli; mazais ārējais skaitlis ir katra elementa kārta.',
      svgAriaLabel: 'Kaklarotas diagramma grupai {group}',
      'notice.heading': 'Grupai {group} nav ģeneratora, tāpēc neviens ceļš nesasniedz visus elementus',
      'notice.body': 'Elementu skaits grupā ir {count}, bet neviens atsevišķs elements nesasniedz tos visus: garākā ceļa garums, sākot no 1, ir {longest}. Grupa ir veidota no cikliskajām grupām {factors}.',
      'notice.whyPowerOfTwo': 'Iemesls: n = {n} ir 2 pakāpe, kas lielāka par 4.',
      'notice.whyFourAndOdd': 'Iemesls: n = {n} dalās ar 4 un ar nepāra pirmskaitli.',
      'notice.whyTwoOddPrimes': 'Iemesls: skaitlim n = {n} ir divi dažādi nepāra pirmreizinātāji.',
      'notice.rule': '(Z/n)* ir cikliska tieši tad, kad n ir 1, 2 vai 4, nepāra pirmskaitļa pakāpe p^k vai tās divkāršs, 2p^k. Aditīvā Z/n vienmēr ir cikliska.',
      exportPng: 'Lejupielādēt apļa PNG',
      exportSaved: 'Saglabāts {filename}.',
      exportFailed: 'Attēlu šajā pārlūkā nevarēja eksportēt.'
    }
});
NT.i18n.register('site', {
    lv: {
      'nav.cyclicGroups': 'Cikliskās grupas'
    }
});
NT.i18n.register('hub', {
    lv: {
      'card.cyclicGroups.title': 'Cikliskās grupas kaklarota',
      'card.cyclicGroups.desc': 'Katrs grupas elements kļūst par krelli uz apļa; sper soļus ar ģeneratoru, un hordas izveido zvaigzni, kas pieskaras katrai krellei — un, kad neviens atsevišķs elements nevar sasniegt tos visus, grupa sadalās mazākos apļos, no kuriem tā ir veidota.'
    }
});
