/* 261009-tgw fragment: nb (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    nb: {
      title: 'Sykliske grupper — Halskjedevisualisering',
      eyebrow: 'gruppeteori · generatorer og baner',
      heading: 'Halskjede for en syklisk gruppe',
      lede: 'Velg en gruppe. Hvert element sitter på en ring, med like stor avstand. Når du går med generatoren, tegnes kordene, og en generator som når hvert element er det som gjør gruppen syklisk. Grupper uten et slikt element deles opp i ringene de er bygget av.',
      xref: 'Se denne gruppens fullstendige operasjonstabell i Cayleytabellen →',
      tablistLabel: 'Gruppeoperasjon',
      groupHeading: 'Gruppe',
      subgroupHeading: 'Undergruppe',
      identityOnly: 'Identiteten genererer bare seg selv',
      nLabel: 'n — modul',
      genLabel: 'Visualisert undergruppe',
      nNoteClamped: 'n går fra 2 til 100, så diagrammet viser n = {n}.',
      layersHeading: 'Lag',
      extraOptions: 'Vis flere alternativer',
      layerCord: 'Vis tilhørende mangekant',
      layerGuide: 'Vis forbindelsessirkel',
      layerElement: 'Sti framover',
      layerElementTitle: 'Å ta et steg er å kombinere det gjeldende elementet med {g}',
      layerBackward: 'Slå av sti bakover',
      layerPaths: 'Undergruppestier',
      resizeTitle: 'Dra for å endre størrelse; dobbeltklikk for å tilbakestille',
      dirLabel: 'Retning framover',
      dirCw: 'Med klokken',
      dirCcw: 'Mot klokken',
      sideInside: 'Innenfor',
      sideOutside: 'Utenfor',
      colorElement: 'Pilfarge for elementet',
      colorInverse: 'Pilfarge for inversen',
      colorReset: 'Tilbakestill pilfarger',
      genTop: 'Roter den valgte generatoren til toppen',
      swapColors: 'Bytt farger på stiene framover og bakover',
      customColors: 'Velg pilfarger manuelt',
      layerColors: 'Elementfarger',
      colorByLabel: 'Farg elementer etter',
      colorByOrder: 'Undergruppens kardinalitet',
      colorByInverse: 'Inverse par',
      layerOrders: 'Ordensetiketter',
      layerBygen: 'Ordne elementer etter potenser av generatoren',
      combineForward: 'Sti framover, kombinerer elementer med det valgte elementet {h}',
      combineBackward: 'Sti bakover, kombinerer elementer med inversen til det valgte elementet, som er {hinv}',
      combineSelfInverse: '{h} er sin egen invers, så begge vandringene er én og samme, tegnet én gang i en blanding av de to fargene',
      factsHeading: 'Denne gruppen',
      cosetButton: 'Utforsk sideklasser',
      cosetHide: 'Slutt å utforske sideklasser',
      cosetNoneGenerator: 'Ingen sideklasser å utforske; {g} er en generator',
      cosetProgress: 'Uthever nå sideklasse {i} av {count}',
      autoRotate: 'Roter automatisk',
      autoRotateOff: 'Av',
      autoRotateCcw: 'Mot klokken',
      autoRotateCw: 'Med klokken',
      rotateLabel: 'Rotasjon — dra ringen',
      rotateBack: 'Roter ett element mot klokken',
      rotateForward: 'Roter ett element med klokken',
      rotateValue: 'Rotasjon i steg',
      rotateReset: 'Tilbakestill',
      subgroupsHeading: 'Undergruppe generert av hvert element',
      autoShift: 'Forskyv sykliske undergrupper automatisk',
      autoShiftTitle: 'Forskyv den genererte sykliske undergruppen automatisk slik at den begynner ved det første elementet ovenfra i retning framover',
      subLayoutLabel: 'Visning',
      subLayoutGrid: 'Rutenett',
      subLayoutList: 'Liste',
      'fact.group': 'Gruppe',
      'fact.elements': 'Elementer',
      'fact.identity': 'Identitet',
      'fact.operation': 'Gruppeoperasjon',
      opAdd: 'addisjon mod {n}',
      opMul: 'multiplikasjon mod {n}',
      'fact.generators': 'Generatorer',
      'fact.structure': 'Struktur',
      factGeneratorsCount: '{count} av {order}',
      factGeneratorsNone: '0 (ikke syklisk)',
      'hint.notCyclic': 'Ikke noe element går til alle de andre elementene: pilene fra 1 kommer alltid tilbake før ringen er full.',
      'hint.noLabels': 'Elementene er for små for tallettiketter her; mønsteret vises likevel.',
      'hint.multiplicative': 'Elementene er tallene under {n} som ikke har noen felles faktor med {n}. Å ta et steg betyr å multiplisere med {g} mod {n}.',
      'hint.additive': 'Å ta et steg betyr å legge til {g} mod {n}.',
      'hint.mirror': 'Inverser speiler hverandre om den stiplede aksen gjennom identiteten; elementet på aksen er sin egen invers.',
      'hint.mirrorOffSorted': 'Elementene er sortert etter verdi, så inverser speiles ikke her.',
      'hint.mirrorOff': 'I denne rekkefølgen er elementene sortert etter verdi, så inverser speiles ikke. Slå på «Ordne elementer etter potenser av generatoren» for å se dem speile om aksen gjennom identiteten.',
      legendHeading: 'Fargenøkkel: undergruppens kardinalitet',
      legendOrder: 'Undergruppens kardinalitet: {order}',
      legendSubgroups: { one: '{count} undergruppe', other: '{count} undergrupper' },
      legendHeadingInverse: 'Fargenøkkel: inverse par',
      legendSelfInverse: 'egen invers: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · element {h} av orden {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, så det er {n} / {size} = {count} sideklasser',
      ringFootnote: 'Identiteten, {id}, er ringet inn.',
      ringFootnoteOrders: 'Identiteten, {id}, er ringet inn; det lille ytre tallet er ordenen til hvert element.',
      svgAriaLabel: 'Halskjedediagram for {group}',
      'notice.heading': '{group} har ingen generator, så ingen vandring når alle elementene',
      'notice.body': 'Gruppen har {count} elementer, men ikke noe enkelt element når alle: den lengste vandringen fra 1 tar {longest} steg. Gruppen er bygget opp av de sykliske gruppene {factors}.',
      'notice.whyPowerOfTwo': 'Hvorfor: n = {n} er en potens av 2 over 4.',
      'notice.whyFourAndOdd': 'Hvorfor: n = {n} er delelig med 4 og med et odde primtall.',
      'notice.whyTwoOddPrimes': 'Hvorfor: n = {n} har to forskjellige odde primfaktorer.',
      'notice.rule': '(Z/n)* er syklisk nøyaktig når n er 1, 2 eller 4, en odde primtallspotens p^k, eller det dobbelte av en slik, 2p^k. Den additive gruppen Z/n er alltid syklisk.',
      exportPng: 'Last ned ring-PNG',
      exportSaved: 'Lagret {filename}.',
      exportFailed: 'Bildet kunne ikke eksporteres i denne nettleseren.'
    }
});
NT.i18n.register('site', {
    nb: {
      'nav.cyclicGroups': 'Sykliske grupper'
    }
});
NT.i18n.register('hub', {
    nb: {
      'card.cyclicGroups.title': 'Halskjede for en syklisk gruppe',
      'card.cyclicGroups.desc': 'Hvert element i en gruppe blir en perle på en ring; ta steg med en generator, så tegner kordene en stjerne som berører hver perle — og når ikke noe enkelt element kan nå dem alle, deles gruppen opp i de mindre ringene den er bygget av.'
    }
});
