/* 261009-tgw fragment: nl (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    nl: {
      title: 'Cyclische groepen — Kettingvisualisatie',
      eyebrow: 'groepentheorie · voortbrengers en banen',
      heading: 'Ketting van een cyclische groep',
      lede: 'Kies een groep. Elk element staat op een ring, op gelijke afstand van elkaar. Als je met de voortbrenger stapt, worden de koorden getekend, en een voortbrenger die elk element bereikt maakt de groep cyclisch. Groepen zonder zo’n element worden opgesplitst in de ringen waaruit ze zijn opgebouwd.',
      xref: 'Bekijk de volledige bewerkingstabel van deze groep in de Cayleytabel →',
      tablistLabel: 'Groepsbewerking',
      groupHeading: 'Groep',
      subgroupHeading: 'Subgroep',
      identityOnly: 'De identiteit brengt alleen zichzelf voort',
      nLabel: 'n — modulus',
      genLabel: 'Weergegeven subgroep',
      nNoteClamped: 'n loopt van 2 tot 100, dus het diagram toont n = {n}.',
      layersHeading: 'Lagen',
      extraOptions: 'Extra opties tonen',
      layerCord: 'Bijbehorende veelhoek tonen',
      layerGuide: 'Verbindingscirkel tonen',
      layerElement: 'Voorwaarts pad',
      layerElementTitle: 'Een stap zetten is het huidige element combineren met {g}',
      layerBackward: 'Achterwaarts pad uitschakelen',
      layerPaths: 'Subgroeppaden',
      resizeTitle: 'Sleep om het formaat te wijzigen; dubbelklik om te herstellen',
      dirLabel: 'Voorwaartse richting',
      dirCw: 'Met de klok mee',
      dirCcw: 'Tegen de klok in',
      sideInside: 'Binnen',
      sideOutside: 'Buiten',
      colorElement: 'Pijlkleur van het element',
      colorInverse: 'Pijlkleur van de inverse',
      colorReset: 'Pijlkleuren herstellen',
      genTop: 'Draai de gekozen voortbrenger naar boven',
      swapColors: 'Kleuren van voorwaarts en achterwaarts pad omwisselen',
      customColors: 'Pijlkleuren handmatig kiezen',
      layerColors: 'Elementkleuren',
      colorByLabel: 'Elementen kleuren op',
      colorByOrder: 'Kardinaliteit van subgroep',
      colorByInverse: 'Inverse paren',
      layerOrders: 'Orde-labels',
      layerBygen: 'Elementen ordenen op machten van de voortbrenger',
      combineForward: 'Voorwaarts pad, elementen combineren met het gekozen element {h}',
      combineBackward: 'Achterwaarts pad, elementen combineren met de inverse van het gekozen element, namelijk {hinv}',
      combineSelfInverse: '{h} is zijn eigen inverse, dus beide wandelingen zijn dezelfde, eenmaal getekend in een mix van de twee kleuren',
      factsHeading: 'Deze groep',
      cosetButton: 'Nevenklassen verkennen',
      cosetHide: 'Stop met nevenklassen verkennen',
      cosetNoneGenerator: 'Geen nevenklassen om te verkennen; {g} is een voortbrenger',
      cosetProgress: 'Nevenklasse {i} van {count} wordt gemarkeerd',
      autoRotate: 'Automatisch draaien',
      autoRotateOff: 'Uit',
      autoRotateCcw: 'Tegen de klok in',
      autoRotateCw: 'Met de klok mee',
      rotateLabel: 'Draaiing — sleep de ring',
      rotateBack: 'Draai één element tegen de klok in',
      rotateForward: 'Draai één element met de klok mee',
      rotateValue: 'Draaiing in stappen',
      rotateReset: 'Herstart',
      subgroupsHeading: 'Subgroep voortgebracht door elk element',
      autoShift: 'Cyclische subgroepen automatisch verschuiven',
      autoShiftTitle: 'Verschuif de voortgebrachte cyclische subgroep automatisch zodat die begint bij het eerste element van bovenaf in de voorwaartse richting',
      subLayoutLabel: 'Weergave',
      subLayoutGrid: 'Raster',
      subLayoutList: 'Lijst',
      'fact.group': 'Groep',
      'fact.elements': 'Elementen',
      'fact.identity': 'Identiteit',
      'fact.operation': 'Bewerking',
      opAdd: 'optelling mod {n}',
      opMul: 'vermenigvuldiging mod {n}',
      'fact.generators': 'Voortbrengers',
      'fact.structure': 'Structuur',
      factGeneratorsCount: '{count} van {order}',
      factGeneratorsNone: '0 (niet cyclisch)',
      'hint.notCyclic': 'Geen enkel element loopt langs alle andere elementen: de pijlen vanaf 1 keren altijd terug voordat de ring vol is.',
      'hint.noLabels': 'De elementen zijn hier te klein voor cijferlabels; het patroon blijft zichtbaar.',
      'hint.multiplicative': 'De elementen zijn de getallen kleiner dan {n} die geen factor met {n} gemeen hebben. Een stap zetten betekent vermenigvuldigen met {g} mod {n}.',
      'hint.additive': 'Een stap zetten betekent {g} optellen mod {n}.',
      'hint.mirror': 'Inversen spiegelen elkaar in de gestippelde as door de identiteit; het element op de as is zijn eigen inverse.',
      'hint.mirrorOffSorted': 'De elementen zijn op waarde gesorteerd, dus inversen spiegelen hier niet.',
      'hint.mirrorOff': 'In deze volgorde zijn de elementen op waarde gesorteerd, dus inversen spiegelen niet. Zet “Elementen ordenen op machten van de voortbrenger” aan om te zien dat ze spiegelen in de as door de identiteit.',
      legendHeading: 'Kleurcode: kardinaliteit van subgroep',
      legendOrder: 'Kardinaliteit van subgroep: {order}',
      legendSubgroups: { one: '{count} subgroep', other: '{count} subgroepen' },
      legendHeadingInverse: 'Kleurcode: inverse paren',
      legendSelfInverse: 'eigen inverse: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · element {h} van orde {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, dus er zijn {n} / {size} = {count} nevenklassen',
      ringFootnote: 'De identiteit, {id}, is omcirkeld.',
      ringFootnoteOrders: 'De identiteit, {id}, is omcirkeld; het kleine getal buiten is de orde van elk element.',
      svgAriaLabel: 'Kettingdiagram van {group}',
      'notice.heading': '{group} heeft geen voortbrenger, dus geen enkele wandeling bereikt alle elementen',
      'notice.body': 'De groep heeft {count} elementen, maar geen enkel element bereikt ze allemaal: de langste wandeling vanaf 1 duurt {longest} stappen. De groep is opgebouwd uit de cyclische groepen {factors}.',
      'notice.whyPowerOfTwo': 'Reden: n = {n} is een macht van 2 groter dan 4.',
      'notice.whyFourAndOdd': 'Reden: n = {n} is deelbaar door 4 en door een oneven priemgetal.',
      'notice.whyTwoOddPrimes': 'Reden: n = {n} heeft twee verschillende oneven priemfactoren.',
      'notice.rule': '(Z/n)* is precies dan cyclisch als n gelijk is aan 1, 2 of 4, een macht p^k van een oneven priemgetal, of tweemaal zo’n macht, 2p^k. De additieve groep Z/n is altijd cyclisch.',
      exportPng: 'PNG van ring downloaden',
      exportSaved: 'Opgeslagen: {filename}.',
      exportFailed: 'De afbeelding kon in deze browser niet worden geëxporteerd.'
    }
});
NT.i18n.register('site', {
    nl: {
      'nav.cyclicGroups': 'Cyclische groepen'
    }
});
NT.i18n.register('hub', {
    nl: {
      'card.cyclicGroups.title': 'Ketting van een cyclische groep',
      'card.cyclicGroups.desc': 'Elk element van een groep wordt een kraal aan een ring; stap met een voortbrenger en de koorden tekenen een ster die elke kraal raakt — en als geen enkel element ze allemaal kan bereiken, splitst de groep zich in de kleinere ringen waaruit hij is opgebouwd.'
    }
});
