/* 261009-tgw fragment: pl (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    pl: {
      title: 'Grupy cykliczne — wizualizator naszyjnika',
      eyebrow: 'teoria grup · generatory i orbity',
      heading: 'Naszyjnik grupy cyklicznej',
      lede: 'Wybierz grupę. Każdy element leży na okręgu, w równych odstępach. Krok o generator rysuje cięciwy, a generator, który dociera do każdego elementu, sprawia, że grupa jest cykliczna. Grupy bez takiego elementu rozpadają się na okręgi, z których są zbudowane.',
      xref: 'Pełną tabelę działania tej grupy zobaczysz w tabeli Cayleya →',
      tablistLabel: 'Działanie grupowe',
      groupHeading: 'Grupa',
      subgroupHeading: 'Podgrupa',
      identityOnly: 'Element neutralny generuje tylko samego siebie',
      nLabel: 'n — moduł',
      genLabel: 'Wizualizowana podgrupa',
      nNoteClamped: 'n przyjmuje wartości od 2 do 100, więc diagram pokazuje n = {n}.',
      layersHeading: 'Nakładki',
      extraOptions: 'Pokaż dodatkowe opcje',
      layerCord: 'Pokaż odpowiadający wielokąt',
      layerGuide: 'Pokaż okrąg łączący',
      layerElement: 'Ścieżka w przód',
      layerElementTitle: 'Zrobienie kroku oznacza połączenie bieżącego elementu z {g}',
      layerBackward: 'Wyłącz ścieżkę wstecz',
      layerPaths: 'Ścieżki podgrupy',
      resizeTitle: 'Przeciągnij, aby zmienić rozmiar; kliknij dwukrotnie, aby zresetować',
      dirLabel: 'Kierunek do przodu',
      dirCw: 'Zgodnie z ruchem wskazówek zegara',
      dirCcw: 'Przeciwnie do ruchu wskazówek zegara',
      sideInside: 'Wewnątrz',
      sideOutside: 'Na zewnątrz',
      colorElement: 'Kolor strzałek elementu',
      colorInverse: 'Kolor strzałek odwrotności',
      colorReset: 'Resetuj kolory strzałek',
      genTop: 'Obróć wybrany generator na górę',
      swapColors: 'Zamień kolory ścieżek w przód i wstecz',
      customColors: 'Wybierz kolory strzałek ręcznie',
      layerColors: 'Kolory elementów',
      colorByLabel: 'Koloruj elementy według',
      colorByOrder: 'Liczność podgrupy',
      colorByInverse: 'Pary elementów odwrotnych',
      layerOrders: 'Etykiety rzędów',
      layerBygen: 'Ułóż elementy według potęg generatora',
      combineForward: 'Ścieżka w przód, łącząca elementy z wybranym elementem {h}',
      combineBackward: 'Ścieżka wstecz, łącząca elementy z odwrotnością wybranego elementu, czyli {hinv}',
      combineSelfInverse: '{h} jest swoją własną odwrotnością, więc oba przejścia są tym samym przejściem, narysowanym raz w mieszance obu kolorów',
      factsHeading: 'Ta grupa',
      cosetButton: 'Zbadaj warstwy',
      cosetHide: 'Przestań badać warstwy',
      cosetNoneGenerator: 'Brak warstw do zbadania; {g} jest generatorem',
      cosetProgress: 'Aktualnie podświetlona warstwa {i} z {count}',
      autoRotate: 'Automatyczny obrót',
      autoRotateOff: 'Wyłączony',
      autoRotateCcw: 'Przeciwnie do ruchu wskazówek zegara',
      autoRotateCw: 'Zgodnie z ruchem wskazówek zegara',
      rotateLabel: 'Obrót — przeciągnij okrąg',
      rotateBack: 'Obróć o jeden element przeciwnie do ruchu wskazówek zegara',
      rotateForward: 'Obróć o jeden element zgodnie z ruchem wskazówek zegara',
      rotateValue: 'Obrót w krokach',
      rotateReset: 'Resetuj',
      subgroupsHeading: 'Podgrupa generowana przez każdy element',
      autoShift: 'Automatycznie przesuwaj podgrupy cykliczne',
      autoShiftTitle: 'Automatycznie przesuwaj wygenerowaną podgrupę cykliczną tak, aby pasowała do pierwszego elementu od góry przy ruchu w kierunku do przodu',
      subLayoutLabel: 'Układ',
      subLayoutGrid: 'Siatka',
      subLayoutList: 'Lista',
      'fact.group': 'Grupa',
      'fact.elements': 'Elementy',
      'fact.identity': 'Element neutralny',
      'fact.operation': 'Działanie',
      opAdd: 'dodawanie mod {n}',
      opMul: 'mnożenie mod {n}',
      'fact.generators': 'Generatory',
      'fact.structure': 'Struktura',
      factGeneratorsCount: '{count} z {order}',
      factGeneratorsNone: '0 (niecykliczna)',
      'hint.notCyclic': 'Żaden element nie dociera do wszystkich pozostałych: strzałki wychodzące z 1 zawsze wracają, zanim okrąg się zapełni.',
      'hint.noLabels': 'Elementy są tu zbyt małe na etykiety z liczbami; wzór nadal jest widoczny.',
      'hint.multiplicative': 'Elementami są liczby mniejsze od {n}, które nie mają z nim wspólnego czynnika. Krok oznacza mnożenie przez {g} mod {n}.',
      'hint.additive': 'Krok oznacza dodanie {g} mod {n}.',
      'hint.mirror': 'Odwrotności odbijają się nawzajem względem przerywanej osi przechodzącej przez element neutralny; element leżący na osi jest swoją własną odwrotnością.',
      'hint.mirrorOffSorted': 'Elementy są posortowane według wartości, więc odwrotności nie odbijają się tu lustrzanie.',
      'hint.mirrorOff': 'W tym układzie elementy są posortowane według wartości, więc odwrotności nie odbijają się lustrzanie. Włącz opcję „Ułóż elementy według potęg generatora”, aby zobaczyć, jak odbijają się względem osi przechodzącej przez element neutralny.',
      legendHeading: 'Legenda kolorów: liczność podgrupy',
      legendOrder: 'Liczność podgrupy: {order}',
      legendSubgroups: { one: '{count} podgrupa', few: '{count} podgrupy', many: '{count} podgrup', other: '{count} podgrup' },
      legendHeadingInverse: 'Legenda kolorów: pary elementów odwrotnych',
      legendSelfInverse: 'własna odwrotność: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · element {h} rzędu {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, więc liczba warstw wynosi {n} / {size} = {count}',
      ringFootnote: 'Element neutralny, {id}, jest otoczony okręgiem.',
      ringFootnoteOrders: 'Element neutralny, {id}, jest otoczony okręgiem; mała liczba na zewnątrz to rząd każdego elementu.',
      svgAriaLabel: 'Diagram naszyjnika grupy {group}',
      'notice.heading': '{group} nie ma generatora, więc żadna ścieżka nie dociera do wszystkich elementów',
      'notice.body': 'Liczba elementów grupy wynosi {count}, ale żaden pojedynczy element nie dociera do wszystkich: długość najdłuższej ścieżki zaczynającej się w 1 to {longest}. Grupa jest zbudowana z grup cyklicznych {factors}.',
      'notice.whyPowerOfTwo': 'Powód: n = {n} jest potęgą liczby 2 większą niż 4.',
      'notice.whyFourAndOdd': 'Powód: n = {n} jest podzielne przez 4 i przez nieparzystą liczbę pierwszą.',
      'notice.whyTwoOddPrimes': 'Powód: n = {n} ma dwa różne nieparzyste czynniki pierwsze.',
      'notice.rule': '(Z/n)* jest cykliczna dokładnie wtedy, gdy n wynosi 1, 2 lub 4, jest potęgą p^k nieparzystej liczby pierwszej albo jej dwukrotnością, 2p^k. Addytywna Z/n jest zawsze cykliczna.',
      exportPng: 'Pobierz PNG okręgu',
      exportSaved: 'Zapisano: {filename}.',
      exportFailed: 'Nie udało się wyeksportować obrazu w tej przeglądarce.'
    }
});
NT.i18n.register('site', {
    pl: {
      'nav.cyclicGroups': 'Grupy cykliczne'
    }
});
NT.i18n.register('hub', {
    pl: {
      'card.cyclicGroups.title': 'Naszyjnik grupy cyklicznej',
      'card.cyclicGroups.desc': 'Każdy element grupy staje się koralikiem na okręgu; zrób krok o generator, a cięciwy utworzą gwiazdę dotykającą każdego koralika — a gdy żaden pojedynczy element nie dociera do wszystkich, grupa rozpada się na mniejsze okręgi, z których jest zbudowana.'
    }
});
