/* 261009-tgw fragment: pt-PT (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    'pt-PT': {
      title: 'Grupos cíclicos — Visualizador de colares',
      eyebrow: 'teoria dos grupos · geradores e órbitas',
      heading: 'Colar do grupo cíclico',
      lede: 'Escolhe um grupo. Cada elemento fica num círculo, a distâncias iguais. Avançar pelo gerador desenha as cordas, e um gerador que alcança todos os elementos é o que torna o grupo cíclico. Os grupos sem um elemento assim dividem-se nos círculos com que são construídos.',
      xref: 'Vê a tabela de operação completa deste grupo na Tabela de Cayley →',
      tablistLabel: 'Operação do grupo',
      groupHeading: 'Grupo',
      subgroupHeading: 'Subgrupo',
      identityOnly: 'O elemento neutro só produz a si próprio',
      nLabel: 'n — módulo',
      genLabel: 'Subgrupo visualizado',
      nNoteClamped: 'n vai de 2 a 100, por isso o diagrama mostra n = {n}.',
      layersHeading: 'Camadas',
      extraOptions: 'Mostrar opções adicionais',
      layerCord: 'Mostrar o polígono correspondente',
      layerGuide: 'Mostrar o círculo que liga os elementos',
      layerElement: 'Caminho de ida',
      layerElementTitle: 'Dar um passo é combinar o elemento atual com {g}',
      layerBackward: 'Desativar o caminho de volta',
      layerPaths: 'Caminhos do subgrupo',
      resizeTitle: 'Arrasta para redimensionar; clica duas vezes para repor',
      dirLabel: 'Direção de ida',
      dirCw: 'Sentido horário',
      dirCcw: 'Sentido anti-horário',
      sideInside: 'Dentro',
      sideOutside: 'Fora',
      colorElement: 'Cor da seta do elemento',
      colorInverse: 'Cor da seta do inverso',
      colorReset: 'Repor as cores das setas',
      genTop: 'Rodar o gerador selecionado para o topo',
      swapColors: 'Trocar as cores dos caminhos de ida e de volta',
      customColors: 'Escolher as cores das setas manualmente',
      layerColors: 'Cores dos elementos',
      colorByLabel: 'Colorir os elementos por',
      colorByOrder: 'Cardinalidade do subgrupo',
      colorByInverse: 'Pares de inversos',
      layerOrders: 'Etiquetas de ordem',
      layerBygen: 'Organizar os elementos por potências do gerador',
      combineForward: 'Caminho de ida, combinando os elementos com o elemento selecionado {h}',
      combineBackward: 'Caminho de volta, combinando os elementos com o inverso do elemento selecionado, que é {hinv}',
      combineSelfInverse: '{h} é o seu próprio inverso, por isso os dois percursos são o mesmo, desenhado uma só vez numa mistura das duas cores',
      factsHeading: 'Este grupo',
      cosetButton: 'Explorar classes laterais',
      cosetHide: 'Parar de explorar classes laterais',
      cosetNoneGenerator: 'Não há classes laterais para explorar; {g} é um gerador',
      cosetProgress: 'A destacar a classe lateral {i} de {count}',
      autoRotate: 'Rotação automática',
      autoRotateOff: 'Desativada',
      autoRotateCcw: 'Sentido anti-horário',
      autoRotateCw: 'Sentido horário',
      rotateLabel: 'Rotação — arrasta o círculo',
      rotateBack: 'Rodar um elemento no sentido anti-horário',
      rotateForward: 'Rodar um elemento no sentido horário',
      rotateValue: 'Rotação em passos',
      rotateReset: 'Repor',
      subgroupsHeading: 'Subgrupo gerado por cada elemento',
      autoShift: 'Deslocar automaticamente os subgrupos cíclicos',
      autoShiftTitle: 'Desloca automaticamente o subgrupo cíclico gerado para que coincida com o primeiro elemento a partir do topo ao avançar na direção de ida',
      subLayoutLabel: 'Disposição',
      subLayoutGrid: 'Grelha',
      subLayoutList: 'Lista',
      'fact.group': 'Grupo',
      'fact.elements': 'Elementos',
      'fact.identity': 'Elemento neutro',
      'fact.operation': 'Operação',
      opAdd: 'adição módulo {n}',
      opMul: 'multiplicação módulo {n}',
      'fact.generators': 'Geradores',
      'fact.structure': 'Estrutura',
      factGeneratorsCount: '{count} de {order}',
      factGeneratorsNone: '0 (não cíclico)',
      'hint.notCyclic': 'Nenhum elemento percorre todos os outros: as setas a partir de 1 voltam sempre antes de o círculo ficar completo.',
      'hint.noLabels': 'Os elementos são demasiado pequenos para etiquetas numéricas aqui; o padrão continua visível.',
      'hint.multiplicative': 'Os elementos são os números menores que {n} que não têm nenhum fator em comum com ele. Avançar significa multiplicar por {g} módulo {n}.',
      'hint.additive': 'Avançar significa somar {g} módulo {n}.',
      'hint.mirror': 'Os inversos espelham-se em relação ao eixo tracejado que passa pelo elemento neutro; o elemento sobre o eixo é o seu próprio inverso.',
      'hint.mirrorOffSorted': 'Os elementos estão ordenados por valor, por isso aqui os inversos não se espelham.',
      'hint.mirrorOff': 'Com esta disposição, os elementos estão ordenados por valor, por isso os inversos não se espelham. Ativa «Organizar os elementos por potências do gerador» para os ver espelharem-se em relação ao eixo que passa pelo elemento neutro.',
      legendHeading: 'Legenda de cores: cardinalidade do subgrupo',
      legendOrder: 'Cardinalidade do subgrupo: {order}',
      legendSubgroups: { one: '{count} subgrupo', other: '{count} subgrupos' },
      legendHeadingInverse: 'Legenda de cores: pares de inversos',
      legendSelfInverse: 'próprio inverso: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · elemento {h} de ordem {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, por isso há {n} / {size} = {count} classes laterais',
      ringFootnote: 'O elemento neutro, {id}, está circundado.',
      ringFootnoteOrders: 'O elemento neutro, {id}, está circundado; o número pequeno exterior é a ordem de cada elemento.',
      svgAriaLabel: 'Diagrama de colar de {group}',
      'notice.heading': '{group} não tem gerador, por isso nenhum percurso alcança todos os elementos',
      'notice.body': 'O grupo tem {count} elementos, mas nenhum elemento sozinho os alcança a todos: o percurso mais longo a partir de 1 leva {longest} passos. O grupo é construído a partir dos grupos cíclicos {factors}.',
      'notice.whyPowerOfTwo': 'Motivo: n = {n} é uma potência de 2 maior que 4.',
      'notice.whyFourAndOdd': 'Motivo: n = {n} é divisível por 4 e por um primo ímpar.',
      'notice.whyTwoOddPrimes': 'Motivo: n = {n} tem dois fatores primos ímpares diferentes.',
      'notice.rule': '(Z/n)* é cíclico exatamente quando n é 1, 2 ou 4, uma potência de primo ímpar p^k, ou o dobro de uma, 2p^k. O grupo aditivo Z/n é sempre cíclico.',
      exportPng: 'Descarregar PNG do círculo',
      exportSaved: 'Guardado {filename}.',
      exportFailed: 'Não foi possível exportar a imagem neste navegador.'
    }
});
NT.i18n.register('site', {
    'pt-PT': {
      'nav.cyclicGroups': 'Grupos cíclicos'
    }
});
NT.i18n.register('hub', {
    'pt-PT': {
      'card.cyclicGroups.title': 'Colar do grupo cíclico',
      'card.cyclicGroups.desc': 'Cada elemento de um grupo torna-se uma conta num círculo; avança por um gerador e as cordas desenham uma estrela que toca em todas as contas — e quando nenhum elemento sozinho as consegue alcançar a todas, o grupo divide-se nos círculos mais pequenos com que é construído.'
    }
});
