/* 261009-tgw fragment: ro (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    ro: {
      title: 'Grupuri ciclice — vizualizator de coliere',
      eyebrow: 'teoria grupurilor · generatori și orbite',
      heading: 'Colierul grupului ciclic',
      lede: 'Alege un grup. Fiecare element stă pe un cerc, la distanțe egale. Mersul cu generatorul desenează coardele, iar un generator care ajunge la fiecare element este cel care face grupul ciclic. Grupurile fără un asemenea element se despart în cercurile din care sunt construite.',
      xref: 'Vezi tabela completă a operației acestui grup în Tabla lui Cayley →',
      tablistLabel: 'Operația grupului',
      groupHeading: 'Grup',
      subgroupHeading: 'Subgrup',
      identityOnly: 'Elementul neutru generează doar pe sine',
      nLabel: 'n — modul',
      genLabel: 'Subgrupul vizualizat',
      nNoteClamped: 'n variază de la 2 la 100, așa că diagrama arată n = {n}.',
      layersHeading: 'Straturi',
      extraOptions: 'Arată opțiuni suplimentare',
      layerCord: 'Arată poligonul corespunzător',
      layerGuide: 'Arată cercul de legătură',
      layerElement: 'Drum înainte',
      layerElementTitle: 'A face un pas înseamnă a combina elementul curent cu {g}',
      layerBackward: 'Dezactivează drumul înapoi',
      layerPaths: 'Drumurile subgrupului',
      resizeTitle: 'Trage pentru a redimensiona; fă dublu clic pentru a reseta',
      dirLabel: 'Direcția înainte',
      dirCw: 'În sensul acelor de ceasornic',
      dirCcw: 'În sens invers acelor de ceasornic',
      sideInside: 'În interior',
      sideOutside: 'În exterior',
      colorElement: 'Culoarea săgeților elementului',
      colorInverse: 'Culoarea săgeților inversului',
      colorReset: 'Resetează culorile săgeților',
      genTop: 'Rotește generatorul selectat în partea de sus',
      swapColors: 'Schimbă între ele culorile drumului înainte și înapoi',
      customColors: 'Alege manual culorile săgeților',
      layerColors: 'Culorile elementelor',
      colorByLabel: 'Colorează elementele după',
      colorByOrder: 'Cardinalul subgrupului',
      colorByInverse: 'Perechi de inverse',
      layerOrders: 'Etichete de ordin',
      layerBygen: 'Aranjează elementele după puterile generatorului',
      combineForward: 'Drum înainte, combinând elementele cu elementul selectat {h}',
      combineBackward: 'Drum înapoi, combinând elementele cu inversul elementului selectat, care este {hinv}',
      combineSelfInverse: '{h} este propriul său invers, așa că ambele parcursuri sunt același, desenat o singură dată într-un amestec al celor două culori',
      factsHeading: 'Acest grup',
      cosetButton: 'Explorează clasele laterale',
      cosetHide: 'Oprește explorarea claselor laterale',
      cosetNoneGenerator: 'Nu există clase laterale de explorat; {g} este generator',
      cosetProgress: 'Se evidențiază clasa laterală {i} din {count}',
      autoRotate: 'Rotire automată',
      autoRotateOff: 'Oprită',
      autoRotateCcw: 'În sens invers acelor de ceasornic',
      autoRotateCw: 'În sensul acelor de ceasornic',
      rotateLabel: 'Rotire — trage cercul',
      rotateBack: 'Rotește cu un element în sens invers acelor de ceasornic',
      rotateForward: 'Rotește cu un element în sensul acelor de ceasornic',
      rotateValue: 'Rotire în pași',
      rotateReset: 'Resetează',
      subgroupsHeading: 'Subgrupul generat de fiecare element',
      autoShift: 'Deplasează automat subgrupurile ciclice',
      autoShiftTitle: 'Deplasează automat subgrupul ciclic generat astfel încât să corespundă primului element de sus, mergând în direcția înainte',
      subLayoutLabel: 'Aranjare',
      subLayoutGrid: 'Grilă',
      subLayoutList: 'Listă',
      'fact.group': 'Grup',
      'fact.elements': 'Elemente',
      'fact.identity': 'Element neutru',
      'fact.operation': 'Operație',
      opAdd: 'adunare mod {n}',
      opMul: 'înmulțire mod {n}',
      'fact.generators': 'Generatori',
      'fact.structure': 'Structură',
      factGeneratorsCount: '{count} din {order}',
      factGeneratorsNone: '0 (nu este ciclic)',
      'hint.notCyclic': 'Niciun element nu ajunge la toate celelalte: săgețile pornite din 1 se întorc mereu înainte ca cercul să fie plin.',
      'hint.noLabels': 'Elementele sunt prea mici pentru etichete numerice aici; modelul tot se vede.',
      'hint.multiplicative': 'Elementele sunt numerele mai mici decât {n} care nu au niciun factor comun cu el. A face un pas înseamnă a înmulți cu {g} mod {n}.',
      'hint.additive': 'A face un pas înseamnă a aduna {g} mod {n}.',
      'hint.mirror': 'Inversele se oglindesc reciproc față de axa întreruptă care trece prin elementul neutru; elementul de pe axă este propriul său invers.',
      'hint.mirrorOffSorted': 'Elementele sunt sortate după valoare, așa că inversele nu se oglindesc aici.',
      'hint.mirrorOff': 'În această ordine elementele sunt sortate după valoare, așa că inversele nu se oglindesc. Activează „Aranjează elementele după puterile generatorului” ca să le vezi oglindindu-se față de axa care trece prin elementul neutru.',
      legendHeading: 'Legenda culorilor: cardinalul subgrupului',
      legendOrder: 'Cardinalul subgrupului: {order}',
      legendSubgroups: { one: '{count} subgrup', few: '{count} subgrupuri', other: '{count} de subgrupuri' },
      legendHeadingInverse: 'Legenda culorilor: perechi de inverse',
      legendSelfInverse: 'propriul invers: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · elementul {h} de ordin {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, deci numărul de clase laterale este {n} / {size} = {count}',
      ringFootnote: 'Elementul neutru, {id}, este încercuit.',
      ringFootnoteOrders: 'Elementul neutru, {id}, este încercuit; numărul mic din exterior este ordinul fiecărui element.',
      svgAriaLabel: 'Diagrama colierului pentru {group}',
      'notice.heading': '{group} nu are generator, deci niciun drum nu ajunge la toate elementele',
      'notice.body': 'Numărul de elemente ale grupului este {count}, dar niciun element singur nu le atinge pe toate: lungimea celui mai lung drum pornind din 1 este {longest}. Grupul este construit din grupurile ciclice {factors}.',
      'notice.whyPowerOfTwo': 'Motivul: n = {n} este o putere a lui 2 mai mare decât 4.',
      'notice.whyFourAndOdd': 'Motivul: n = {n} este divizibil cu 4 și cu un număr prim impar.',
      'notice.whyTwoOddPrimes': 'Motivul: n = {n} are doi factori primi impari diferiți.',
      'notice.rule': '(Z/n)* este ciclic exact atunci când n este 1, 2 sau 4, o putere p^k a unui număr prim impar, sau dublul uneia, 2p^k. Z/n aditiv este întotdeauna ciclic.',
      exportPng: 'Descarcă PNG-ul cercului',
      exportSaved: 'Salvat {filename}.',
      exportFailed: 'Imaginea nu a putut fi exportată în acest browser.'
    }
});
NT.i18n.register('site', {
    ro: {
      'nav.cyclicGroups': 'Grupuri ciclice'
    }
});
NT.i18n.register('hub', {
    ro: {
      'card.cyclicGroups.title': 'Colierul grupului ciclic',
      'card.cyclicGroups.desc': 'Fiecare element al unui grup devine o mărgică pe un cerc; fă pași cu un generator și coardele trasează o stea care atinge fiecare mărgică — iar când niciun element singur nu le poate atinge pe toate, grupul se desparte în cercurile mai mici din care este construit.'
    }
});
