/* 261009-tgw fragment: sq (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    sq: {
      title: 'Grupet ciklike — Vizualizuesi i gjerdanit',
      eyebrow: 'teoria e grupeve · gjeneratorët dhe orbitat',
      heading: 'Gjerdani i grupit ciklik',
      lede: 'Zgjidhni një grup. Çdo element qëndron mbi një unazë, në largësi të barabarta. Ecja me gjeneratorin vizaton kordat, dhe një gjenerator që arrin çdo element e bën grupin ciklik. Grupet pa një element të tillë ndahen në unazat nga të cilat janë ndërtuar.',
      xref: 'Shihni tabelën e plotë të veprimit të këtij grupi te Tabela e Cayley-t →',
      tablistLabel: 'Veprimi i grupit',
      groupHeading: 'Grupi',
      subgroupHeading: 'Nëngrupi',
      identityOnly: 'Elementi neutral prodhon vetëm veten',
      nLabel: 'n — moduli',
      genLabel: 'Nëngrupi i vizualizuar',
      nNoteClamped: 'n shkon nga 2 deri në 100, prandaj diagrami tregon n = {n}.',
      layersHeading: 'Shtresat',
      extraOptions: 'Shfaq opsione shtesë',
      layerCord: 'Shfaq shumëkëndëshin përkatës',
      layerGuide: 'Shfaq rrethin lidhës',
      layerElement: 'Shtegu përpara',
      layerElementTitle: 'Të bësh një hap do të thotë të kombinosh elementin aktual me {g}',
      layerBackward: 'Çaktivizo shtegun mbrapsht',
      layerPaths: 'Shtigjet e nëngrupit',
      resizeTitle: 'Tërhiqeni për të ndryshuar madhësinë; klikoni dy herë për ta rivendosur',
      dirLabel: 'Drejtimi përpara',
      dirCw: 'Në drejtim orar',
      dirCcw: 'Në drejtim kundërorar',
      sideInside: 'Brenda',
      sideOutside: 'Jashtë',
      colorElement: 'Ngjyra e shigjetës së elementit',
      colorInverse: 'Ngjyra e shigjetës së të anasjelltit',
      colorReset: 'Rivendos ngjyrat e shigjetave',
      genTop: 'Rrotullo gjeneratorin e zgjedhur lart',
      swapColors: 'Ndërro ngjyrat e shtegut përpara dhe mbrapsht',
      customColors: 'Zgjidh ngjyrat e shigjetave manualisht',
      layerColors: 'Ngjyrat e elementeve',
      colorByLabel: 'Ngjyros elementet sipas',
      colorByOrder: 'Kardinaliteti i nëngrupit',
      colorByInverse: 'Çiftet e të anasjellteve',
      layerOrders: 'Etiketat e rendit',
      layerBygen: 'Rendit elementet sipas fuqive të gjeneratorit',
      combineForward: 'Shtegu përpara, duke kombinuar elementet me elementin e zgjedhur {h}',
      combineBackward: 'Shtegu mbrapsht, duke kombinuar elementet me të anasjelltin e elementit të zgjedhur, që është {hinv}',
      combineSelfInverse: '{h} është i anasjellti i vetes, prandaj të dyja ecjet janë e njëjta, e vizatuar një herë në një përzierje të dy ngjyrave',
      factsHeading: 'Ky grup',
      cosetButton: 'Eksploro klasat fqinje',
      cosetHide: 'Ndalo eksplorimin e klasave fqinje',
      cosetNoneGenerator: 'Nuk ka klasa fqinje për të eksploruar; {g} është gjenerator',
      cosetProgress: 'Tani po theksohet klasa fqinje {i} nga {count}',
      autoRotate: 'Rrotullim automatik',
      autoRotateOff: 'Fikur',
      autoRotateCcw: 'Në drejtim kundërorar',
      autoRotateCw: 'Në drejtim orar',
      rotateLabel: 'Rrotullimi — tërhiqeni unazën',
      rotateBack: 'Rrotullo një element në drejtim kundërorar',
      rotateForward: 'Rrotullo një element në drejtim orar',
      rotateValue: 'Rrotullimi në hapa',
      rotateReset: 'Rivendos',
      subgroupsHeading: 'Nëngrupi i gjeneruar nga çdo element',
      autoShift: 'Zhvendos automatikisht nëngrupet ciklike',
      autoShiftTitle: 'Zhvendos automatikisht nëngrupin ciklik të gjeneruar që të përputhet me elementin e parë nga maja kur lëvizet në drejtimin përpara',
      subLayoutLabel: 'Paraqitja',
      subLayoutGrid: 'Rrjetë',
      subLayoutList: 'Listë',
      'fact.group': 'Grupi',
      'fact.elements': 'Elementet',
      'fact.identity': 'Elementi neutral',
      'fact.operation': 'Veprimi',
      opAdd: 'mbledhje mod {n}',
      opMul: 'shumëzim mod {n}',
      'fact.generators': 'Gjeneratorët',
      'fact.structure': 'Struktura',
      factGeneratorsCount: '{count} nga {order}',
      factGeneratorsNone: '0 (jo ciklik)',
      'hint.notCyclic': 'Asnjë element nuk arrin te të gjithë elementët e tjerë: shigjetat nga 1 kthehen gjithmonë para se unaza të mbushet.',
      'hint.noLabels': 'Elementet janë shumë të vegjël për etiketa numrash këtu; modeli prapë duket.',
      'hint.multiplicative': 'Elementet janë numrat nën {n} që nuk kanë asnjë faktor të përbashkët me të. Të bësh një hap do të thotë të shumëzosh me {g} mod {n}.',
      'hint.additive': 'Të bësh një hap do të thotë të mbledhësh {g} mod {n}.',
      'hint.mirror': 'Të anasjelltit pasqyrohen nga njëri-tjetri përtej boshtit të ndërprerë që kalon nga elementi neutral; elementi mbi bosht është i anasjellti i vetes.',
      'hint.mirrorOffSorted': 'Elementet janë të renditur sipas vlerës, ndaj të anasjelltit nuk pasqyrohen këtu.',
      'hint.mirrorOff': 'Në këtë renditje elementet janë të renditur sipas vlerës, ndaj të anasjelltit nuk pasqyrohen. Aktivizoni „Rendit elementet sipas fuqive të gjeneratorit“ për të parë se si pasqyrohen përtej boshtit që kalon nga elementi neutral.',
      legendHeading: 'Çelësi i ngjyrave: kardinaliteti i nëngrupit',
      legendOrder: 'Kardinaliteti i nëngrupit: {order}',
      legendSubgroups: { one: '{count} nëngrup', other: '{count} nëngrupe' },
      legendHeadingInverse: 'Çelësi i ngjyrave: çiftet e të anasjellteve',
      legendSelfInverse: 'i anasjellti i vetes: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · elementi {h} me rend {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, pra ka {n} / {size} = {count} klasa fqinje',
      ringFootnote: 'Elementi neutral, {id}, është i rrethuar.',
      ringFootnoteOrders: 'Elementi neutral, {id}, është i rrethuar; numri i vogël jashtë është rendi i secilit element.',
      svgAriaLabel: 'Diagrami i gjerdanit të {group}',
      'notice.heading': '{group} nuk ka gjenerator, ndaj asnjë ecje nuk arrin çdo element',
      'notice.body': 'Grupi ka {count} elemente, por asnjë element i vetëm nuk i arrin të gjithë: ecja më e gjatë nga 1 merr {longest} hapa. Grupi ndërtohet nga grupet ciklike {factors}.',
      'notice.whyPowerOfTwo': 'Arsyeja: n = {n} është fuqi e numrit 2 mbi 4.',
      'notice.whyFourAndOdd': 'Arsyeja: n = {n} pjesëtohet me 4 dhe me një numër të thjeshtë tek.',
      'notice.whyTwoOddPrimes': 'Arsyeja: n = {n} ka dy faktorë të thjeshtë tek të ndryshëm.',
      'notice.rule': '(Z/n)* është ciklik saktësisht kur n është 1, 2 ose 4, një fuqi e një numri të thjeshtë tek p^k, ose dyfishi i saj, 2p^k. Z/n aditiv është gjithmonë ciklik.',
      exportPng: 'Shkarko PNG të unazës',
      exportSaved: 'U ruajt {filename}.',
      exportFailed: 'Fotografia nuk mund të eksportohej në këtë shfletues.'
    }
});
NT.i18n.register('site', {
    sq: {
      'nav.cyclicGroups': 'Grupet ciklike'
    }
});
NT.i18n.register('hub', {
    sq: {
      'card.cyclicGroups.title': 'Gjerdani i grupit ciklik',
      'card.cyclicGroups.desc': 'Çdo element i një grupi bëhet rruazë mbi një unazë; hidhni hapa me një gjenerator dhe kordat vizatojnë një yll që prek çdo rruazë — dhe kur asnjë element i vetëm nuk i arrin dot të gjitha, grupi ndahet në unazat më të vogla nga të cilat është ndërtuar.'
    }
});
