/* 261009-tgw fragment: sv (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    sv: {
      title: 'Cykliska grupper — Halsbandsvisualisering',
      eyebrow: 'grupteori · generatorer och banor',
      heading: 'Halsband för en cyklisk grupp',
      lede: 'Välj en grupp. Varje element sitter på en ring, med lika stort avstånd. När du går med generatorn ritas kordorna, och en generator som når varje element är det som gör gruppen cyklisk. Grupper utan ett sådant element delas upp i de ringar de är byggda av.',
      xref: 'Se den här gruppens fullständiga operationstabell i Cayleytabellen →',
      tablistLabel: 'Gruppoperation',
      groupHeading: 'Grupp',
      subgroupHeading: 'Delgrupp',
      identityOnly: 'Identiteten genererar bara sig själv',
      nLabel: 'n — modul',
      genLabel: 'Visualiserad delgrupp',
      nNoteClamped: 'n går från 2 till 100, så diagrammet visar n = {n}.',
      layersHeading: 'Lager',
      extraOptions: 'Visa fler alternativ',
      layerCord: 'Visa motsvarande månghörning',
      layerGuide: 'Visa förbindelsecirkel',
      layerElement: 'Framåtväg',
      layerElementTitle: 'Att ta ett steg är att kombinera det aktuella elementet med {g}',
      layerBackward: 'Inaktivera bakåtväg',
      layerPaths: 'Delgruppsvägar',
      resizeTitle: 'Dra för att ändra storlek; dubbelklicka för att återställa',
      dirLabel: 'Framåtriktning',
      dirCw: 'Medurs',
      dirCcw: 'Moturs',
      sideInside: 'Innanför',
      sideOutside: 'Utanför',
      colorElement: 'Elementets pilfärg',
      colorInverse: 'Inversens pilfärg',
      colorReset: 'Återställ pilfärger',
      genTop: 'Vrid den valda generatorn till toppen',
      swapColors: 'Byt färger på framåt- och bakåtvägen',
      customColors: 'Välj pilfärger manuellt',
      layerColors: 'Elementfärger',
      colorByLabel: 'Färglägg element efter',
      colorByOrder: 'Delgruppens kardinalitet',
      colorByInverse: 'Inversa par',
      layerOrders: 'Ordningsetiketter',
      layerBygen: 'Ordna element efter generatorns potenser',
      combineForward: 'Framåtväg, kombinerar element med det valda elementet {h}',
      combineBackward: 'Bakåtväg, kombinerar element med det valda elementets invers, som är {hinv}',
      combineSelfInverse: '{h} är sin egen invers, så båda vandringarna är en och samma, ritad en gång i en blandning av de två färgerna',
      factsHeading: 'Den här gruppen',
      cosetButton: 'Utforska sidoklasser',
      cosetHide: 'Sluta utforska sidoklasser',
      cosetNoneGenerator: 'Inga sidoklasser att utforska; {g} är en generator',
      cosetProgress: 'Markerar just nu sidoklass {i} av {count}',
      autoRotate: 'Rotera automatiskt',
      autoRotateOff: 'Av',
      autoRotateCcw: 'Moturs',
      autoRotateCw: 'Medurs',
      rotateLabel: 'Rotation — dra ringen',
      rotateBack: 'Rotera ett element moturs',
      rotateForward: 'Rotera ett element medurs',
      rotateValue: 'Rotation i steg',
      rotateReset: 'Återställ',
      subgroupsHeading: 'Delgrupp som genereras av varje element',
      autoShift: 'Förskjut cykliska delgrupper automatiskt',
      autoShiftTitle: 'Förskjut automatiskt den genererade cykliska delgruppen så att den börjar vid det första elementet uppifrån i framåtriktningen',
      subLayoutLabel: 'Visning',
      subLayoutGrid: 'Rutnät',
      subLayoutList: 'Lista',
      'fact.group': 'Grupp',
      'fact.elements': 'Element',
      'fact.identity': 'Identitet',
      'fact.operation': 'Gruppoperation',
      opAdd: 'addition modulo {n}',
      opMul: 'multiplikation modulo {n}',
      'fact.generators': 'Generatorer',
      'fact.structure': 'Struktur',
      factGeneratorsCount: '{count} av {order}',
      factGeneratorsNone: '0 (inte cyklisk)',
      'hint.notCyclic': 'Inget element vandrar till alla andra element: pilarna från 1 återvänder alltid innan ringen är full.',
      'hint.noLabels': 'Elementen är för små för sifferetiketter här; mönstret syns ändå.',
      'hint.multiplicative': 'Elementen är de tal under {n} som inte delar någon faktor med {n}. Att ta ett steg betyder att multiplicera med {g} mod {n}.',
      'hint.additive': 'Att ta ett steg betyder att addera {g} mod {n}.',
      'hint.mirror': 'Inverser speglar varandra över den streckade axeln genom identiteten; elementet på axeln är sin egen invers.',
      'hint.mirrorOffSorted': 'Elementen är sorterade efter värde, så inverser speglas inte här.',
      'hint.mirrorOff': 'I den här ordningen är elementen sorterade efter värde, så inverser speglas inte. Slå på ”Ordna element efter generatorns potenser” för att se dem speglas över axeln genom identiteten.',
      legendHeading: 'Färgnyckel: delgruppens kardinalitet',
      legendOrder: 'Delgruppens kardinalitet: {order}',
      legendSubgroups: { one: '{count} delgrupp', other: '{count} delgrupper' },
      legendHeadingInverse: 'Färgnyckel: inversa par',
      legendSelfInverse: 'egen invers: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · element {h} av ordning {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, så det finns {n} / {size} = {count} sidoklasser',
      ringFootnote: 'Identiteten, {id}, är inringad.',
      ringFootnoteOrders: 'Identiteten, {id}, är inringad; det lilla yttre talet är varje elements ordning.',
      svgAriaLabel: 'Halsbandsdiagram för {group}',
      'notice.heading': '{group} har ingen generator, så ingen vandring når alla element',
      'notice.body': 'Gruppen har {count} element, men inget enskilt element når alla: den längsta vandringen från 1 tar {longest} steg. Gruppen är byggd av de cykliska grupperna {factors}.',
      'notice.whyPowerOfTwo': 'Varför: n = {n} är en potens av 2 över 4.',
      'notice.whyFourAndOdd': 'Varför: n = {n} är delbart med 4 och med ett udda primtal.',
      'notice.whyTwoOddPrimes': 'Varför: n = {n} har två olika udda primfaktorer.',
      'notice.rule': '(Z/n)* är cyklisk precis när n är 1, 2 eller 4, en udda primtalspotens p^k, eller två gånger en sådan, 2p^k. Den additiva gruppen Z/n är alltid cyklisk.',
      exportPng: 'Ladda ner ring-PNG',
      exportSaved: 'Sparade {filename}.',
      exportFailed: 'Bilden kunde inte exporteras i den här webbläsaren.'
    }
});
NT.i18n.register('site', {
    sv: {
      'nav.cyclicGroups': 'Cykliska grupper'
    }
});
NT.i18n.register('hub', {
    sv: {
      'card.cyclicGroups.title': 'Halsband för en cyklisk grupp',
      'card.cyclicGroups.desc': 'Varje element i en grupp blir en pärla på en ring; ta steg med en generator så ritar kordorna en stjärna som rör vid varje pärla — och när inget enskilt element kan nå dem alla delas gruppen upp i de mindre ringar den är byggd av.'
    }
});
