/* 261009-tgw fragment: sw (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    sw: {
      title: 'Makundi ya mzunguko — Kionyeshi cha mkufu',
      eyebrow: 'nadharia ya makundi · vizalishi na obiti',
      heading: 'Mkufu wa kundi la mzunguko',
      lede: 'Chagua kundi. Kila kipengele kiko kwenye pete, kwa nafasi sawa. Kutembea kwa kizalishi huchora kamba, na kizalishi kinachofikia kila kipengele ndicho kinachofanya kundi liwe la mzunguko. Makundi yasiyo na kipengele kama hicho hugawanywa katika pete ambazo yamejengwa kutokana nazo.',
      xref: 'Tazama jedwali kamili la operesheni ya kundi hili katika Jedwali la Cayley →',
      tablistLabel: 'Operesheni ya kundi',
      groupHeading: 'Kundi',
      subgroupHeading: 'Kundi dogo',
      identityOnly: 'Kipengele cha utambulisho huzalisha chenyewe tu',
      nLabel: 'n — moduli',
      genLabel: 'Kundi dogo linaloonyeshwa',
      nNoteClamped: 'n ni kati ya 2 na 100, kwa hiyo mchoro unaonyesha n = {n}.',
      layersHeading: 'Tabaka',
      extraOptions: 'Onyesha chaguo za ziada',
      layerCord: 'Onyesha poligoni inayolingana',
      layerGuide: 'Onyesha duara linalounganisha',
      layerElement: 'Njia ya mbele',
      layerElementTitle: 'Kupiga hatua ni kuchanganya kipengele cha sasa na {g}',
      layerBackward: 'Zima njia ya nyuma',
      layerPaths: 'Njia za kundi dogo',
      resizeTitle: 'Buruta ili kubadilisha ukubwa; bofya mara mbili ili kuweka upya',
      dirLabel: 'Mwelekeo wa mbele',
      dirCw: 'Kuelekea saa',
      dirCcw: 'Kinyume cha saa',
      sideInside: 'Ndani',
      sideOutside: 'Nje',
      colorElement: 'Rangi ya mshale wa kipengele',
      colorInverse: 'Rangi ya mshale wa kinyume',
      colorReset: 'Weka upya rangi za mishale',
      genTop: 'Zungusha kizalishi kilichochaguliwa juu',
      swapColors: 'Badilishana rangi za njia ya mbele na ya nyuma',
      customColors: 'Chagua rangi za mishale mwenyewe',
      layerColors: 'Rangi za vipengele',
      colorByLabel: 'Panga rangi za vipengele kwa',
      colorByOrder: 'Idadi ya vipengele vya kundi dogo',
      colorByInverse: 'Jozi za kinyume',
      layerOrders: 'Lebo za daraja',
      layerBygen: 'Panga vipengele kwa vipeo vya kizalishi',
      combineForward: 'Njia ya mbele, ikichanganya vipengele na kipengele kilichochaguliwa {h}',
      combineBackward: 'Njia ya nyuma, ikichanganya vipengele na kinyume cha kipengele kilichochaguliwa, ambacho ni {hinv}',
      combineSelfInverse: '{h} ni kinyume cha chenyewe, kwa hiyo matembezi yote mawili ni yale yale, yanayochorwa mara moja kwa mchanganyiko wa rangi hizo mbili',
      factsHeading: 'Kundi hili',
      cosetButton: 'Chunguza kosesi',
      cosetHide: 'Acha kuchunguza kosesi',
      cosetNoneGenerator: 'Hakuna kosesi za kuchunguza; {g} ni kizalishi',
      cosetProgress: 'Kwa sasa inaangaziwa kosesi {i} kati ya {count}',
      autoRotate: 'Kuzunguka kiotomatiki',
      autoRotateOff: 'Imezimwa',
      autoRotateCcw: 'Kinyume cha saa',
      autoRotateCw: 'Kuelekea saa',
      rotateLabel: 'Mzunguko — buruta pete',
      rotateBack: 'Zungusha kipengele kimoja kinyume cha saa',
      rotateForward: 'Zungusha kipengele kimoja kuelekea saa',
      rotateValue: 'Mzunguko kwa hatua',
      rotateReset: 'Weka upya',
      subgroupsHeading: 'Kundi dogo linalozalishwa na kila kipengele',
      autoShift: 'Sogeza makundi madogo ya mzunguko kiotomatiki',
      autoShiftTitle: 'Sogeza kiotomatiki kundi dogo la mzunguko lililozalishwa lilingane na kipengele cha kwanza kutoka juu unaposonga mwelekeo wa mbele',
      subLayoutLabel: 'Mpangilio',
      subLayoutGrid: 'Gridi',
      subLayoutList: 'Orodha',
      'fact.group': 'Kundi',
      'fact.elements': 'Vipengele',
      'fact.identity': 'Utambulisho',
      'fact.operation': 'Operesheni',
      opAdd: 'kujumlisha mod {n}',
      opMul: 'kuzidisha mod {n}',
      'fact.generators': 'Vizalishi',
      'fact.structure': 'Muundo',
      factGeneratorsCount: '{count} kati ya {order}',
      factGeneratorsNone: '0 (si la mzunguko)',
      'hint.notCyclic': 'Hakuna kipengele kinachofikia vingine vyote: mishale kutoka 1 hurudi kabla pete haijajaa.',
      'hint.noLabels': 'Vipengele ni vidogo mno kwa lebo za namba hapa; mchoro bado unaonekana.',
      'hint.multiplicative': 'Vipengele ni namba ndogo kuliko {n} zisizo na kigawo cha pamoja nayo. Kupiga hatua ni kuzidisha kwa {g} mod {n}.',
      'hint.additive': 'Kupiga hatua ni kujumlisha {g} mod {n}.',
      'hint.mirror': 'Vinyume huakisiana pande mbili za mhimili wenye vitone unaopitia utambulisho; kipengele kilicho kwenye mhimili ni kinyume cha chenyewe.',
      'hint.mirrorOffSorted': 'Vipengele vimepangwa kwa thamani, kwa hiyo vinyume haviakisiani hapa.',
      'hint.mirrorOff': 'Katika mpangilio huu vipengele vimepangwa kwa thamani, kwa hiyo vinyume haviakisiani. Washa “Panga vipengele kwa vipeo vya kizalishi” ili kuviona vikiakisiana pande mbili za mhimili unaopitia utambulisho.',
      legendHeading: 'Funguo za rangi: idadi ya vipengele vya kundi dogo',
      legendOrder: 'Idadi ya vipengele vya kundi dogo: {order}',
      legendSubgroups: { one: 'kundi dogo {count}', other: 'makundi madogo {count}' },
      legendHeadingInverse: 'Funguo za rangi: jozi za kinyume',
      legendSelfInverse: 'kinyume cha chenyewe: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · kipengele {h} chenye daraja {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, kwa hiyo kuna kosesi {n} / {size} = {count}',
      ringFootnote: 'Utambulisho, {id}, umezungushiwa duara.',
      ringFootnoteOrders: 'Utambulisho, {id}, umezungushiwa duara; namba ndogo ya nje ni daraja la kila kipengele.',
      svgAriaLabel: 'Mchoro wa mkufu wa {group}',
      'notice.heading': '{group} haina kizalishi, kwa hiyo hakuna matembezi yanayofikia kila kipengele',
      'notice.body': 'Kundi lina vipengele {count}, lakini hakuna kipengele kimoja kinachovifikia vyote: matembezi marefu zaidi kutoka 1 huchukua hatua {longest}. Kundi hili limejengwa kutokana na makundi ya mzunguko {factors}.',
      'notice.whyPowerOfTwo': 'Sababu: n = {n} ni nguvu ya 2 iliyo juu ya 4.',
      'notice.whyFourAndOdd': 'Sababu: n = {n} inagawanyika kwa 4 na kwa namba tasa witiri.',
      'notice.whyTwoOddPrimes': 'Sababu: n = {n} ina vigawo viwili tofauti vya namba tasa witiri.',
      'notice.rule': '(Z/n)* ni la mzunguko hasa pale n ni 1, 2 au 4, nguvu ya namba tasa witiri p^k, au mara mbili yake, 2p^k. Z/n ya kujumlisha daima ni la mzunguko.',
      exportPng: 'Pakua PNG ya pete',
      exportSaved: 'Imehifadhiwa {filename}.',
      exportFailed: 'Picha haikuweza kuhamishwa katika kivinjari hiki.'
    }
});
NT.i18n.register('site', {
    sw: {
      'nav.cyclicGroups': 'Makundi ya mzunguko'
    }
});
NT.i18n.register('hub', {
    sw: {
      'card.cyclicGroups.title': 'Mkufu wa kundi la mzunguko',
      'card.cyclicGroups.desc': 'Kila kipengele cha kundi kinakuwa ushanga kwenye pete; piga hatua kwa kizalishi na kamba zinachora nyota inayogusa kila ushanga — na pale kipengele kimoja hakiwezi kuvifikia vyote, kundi hugawanyika katika pete ndogo ambazo limejengwa kutokana nazo.'
    }
});
