/* 261009-tgw fragment: zgh-Latn (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    'zgh-Latn': {
      title: 'Tigrawin tisutlanin — Asskan n taqlada',
      eyebrow: 'tiẓri n tgrawin · imsnulfuyn d ibriden',
      heading: 'Taqlada n tgrawt tasutlant',
      lede: 'Sti yat tgrawt. Yal afrdis ittwasbdd ɣ yat twrirt, s umsawa gr ifrdisn. Tikli s umsnulfu ar tsnlf iwtarn, dɣa amsnulfu ar iwwiḍ ɣr yal afrdis ayd ar iskar tagrawt d tasutlant. Tigrawin war sɛan afrdis am wa ar ttwabḍant ɣr twririn ayd tgant.',
      xref: 'Ẓr taflwit n tmhlt tummidt n tgrawt ad g allal Taflwit n Kayli →',
      tablistLabel: 'Tamhlt n tgrawt',
      groupHeading: 'Tagrawt',
      subgroupHeading: 'Tagrawt tamẓẓit',
      identityOnly: 'Afrdis arawsan ar isnlf kigan iman nnes',
      nLabel: 'n — amuḍul',
      genLabel: 'Tagrawt tamẓẓit ittwaskan',
      nNoteClamped: 'n ixṣṣa ad yili gr 2 d 100, dɣa amskan ar issken n = {n}.',
      layersHeading: 'Tiṭbaqin',
      extraOptions: 'Ssken tifrayin nniḍen',
      layerCord: 'Ssken abulignun n ifrdisn',
      layerGuide: 'Ssken tawrerrayt n ifrdisn',
      layerElement: 'Abrid n zdat',
      layerElementTitle: 'Asurif yan ar iga asmun n ufrdis n tura d {g}',
      layerBackward: 'Ssbdd abrid n uɣal',
      layerPaths: 'Ibriden n tgrawt tamẓẓit',
      resizeTitle: 'Zzuzr bac ad tbddlt tmqqrant; sit snat n tikkal bac ad tssuɣlt',
      dirLabel: 'Tama n zdat',
      dirCw: 'Am ifassn n tswiɛt',
      dirCcw: 'Mgal ifassn n tswiɛt',
      sideInside: 'Daxl',
      sideOutside: 'Brra',
      colorElement: 'Alun n usahm n ufrdis',
      colorInverse: 'Alun n usahm n umgal',
      colorReset: 'Ssuɣl ilwan n isahmn',
      genTop: 'Dwr amsnulfu ittwasti ɣr ufella',
      swapColors: 'Snfl ilwan n ubrid n zdat d ubrid n uɣal',
      customColors: 'Sti ilwan n isahmn s ufus',
      layerColors: 'Ilwan n ifrdisn',
      colorByLabel: 'Ssalun ifrdisn ɣf',
      colorByOrder: 'Amḍan n ifrdisn n tgrawt tamẓẓit',
      colorByInverse: 'Tiyugiwin n imgalnin',
      layerOrders: 'Imḍanen n urdr',
      layerBygen: 'Sbdd ifrdisn s tizmrin n umsnulfu',
      combineForward: 'Abrid n zdat, ar ismun ifrdisn d ufrdis ittwasti {h}',
      combineBackward: 'Abrid n uɣal, ar ismun ifrdisn d umgal n ufrdis ittwasti, ayd iga {hinv}',
      combineSelfInverse: '{h} d amgal n iman nnes, dɣa sin tikliwin d yat, ar ttwaru yat n tikkelt s lxlita n sin ilwan',
      factsHeading: 'Tagrawt ad',
      cosetButton: 'Rzu tiggayin',
      cosetHide: 'Ssbdd arzu n tiggayin',
      cosetNoneGenerator: 'War tiggayin i trzut; {g} d amsnulfu',
      cosetProgress: 'Tura ar ittwakkan taggayt {i} sg {count}',
      autoRotate: 'Adwar awtumatik',
      autoRotateOff: 'Immdl',
      autoRotateCcw: 'Mgal ifassn n tswiɛt',
      autoRotateCw: 'Am ifassn n tswiɛt',
      rotateLabel: 'Adwar — zzuzr twrirt',
      rotateBack: 'Dwr yan ufrdis mgal ifassn n tswiɛt',
      rotateForward: 'Dwr yan ufrdis am ifassn n tswiɛt',
      rotateValue: 'Adwar s isurifn',
      rotateReset: 'Ssuɣl',
      subgroupsHeading: 'Tagrawt tamẓẓit ittwasnlfn s yal afrdis',
      autoShift: 'Bddl amkan n tigrawin timẓẓiyin tisutlanin s uwtumatik',
      autoShiftTitle: 'Bddl s uwtumatik amkan n tgrawt tamẓẓit tasutlant ittwasnlfn, bac ad tmsawa d ufrdis amzwaru sg ufella ticki ar tddut s tama n zdat',
      subLayoutLabel: 'Askil',
      subLayoutGrid: 'Tacbakt',
      subLayoutList: 'Tabdart',
      'fact.group': 'Tagrawt',
      'fact.elements': 'Ifrdisn',
      'fact.identity': 'Afrdis arawsan',
      'fact.operation': 'Tamhlt',
      opAdd: 'asmrni s umuḍul {n}',
      opMul: 'asgut s umuḍul {n}',
      'fact.generators': 'Imsnulfuyn',
      'fact.structure': 'Tuddsa',
      factGeneratorsCount: '{count} sg {order}',
      factGeneratorsNone: '0 (ur d tasutlant)',
      'hint.notCyclic': 'War yan ufrdis ar iwwiḍ ɣr yal afrdis nniḍen: isahmn sg 1 ar d ttuɣaln zzat ad tmmd twrirt.',
      'hint.noLabels': 'Ifrdisn imẓẓin bahra i uskan n imḍanen dagi; ɣas talɣa ar ittwaẓr.',
      'hint.multiplicative': 'Ifrdisn d imḍanen ddaw {n} ur mcrikn afaktur d {n}. Asurif yan d asgut s {g} s umuḍul {n}.',
      'hint.additive': 'Asurif yan d asmrni s {g} s umuḍul {n}.',
      'hint.mirror': 'Imgalnin ar ssmgaln iman nsn ɣf umiḥwar ittwabḍan ittkkan ɣr ufrdis arawsan; afrdis ɣf umiḥwar d amgal n iman nnes.',
      'hint.mirrorOffSorted': 'Ifrdisn ittwasbddn s uzal, dɣa imgalnin ur ssmgaln iman nsn dagi.',
      'hint.mirrorOff': 'S usbdd ad, ifrdisn ittwasbddn s uzal, dɣa imgalnin ur ssmgaln iman nsn. Sti «Sbdd ifrdisn s tizmrin n umsnulfu» bac ad tẓrt amek ar ssmgaln iman nsn ɣf umiḥwar ittkkan ɣr ufrdis arawsan.',
      legendHeading: 'Tasarut n ilwan: amḍan n ifrdisn n tgrawt tamẓẓit',
      legendOrder: 'Amḍan n ifrdisn n tgrawt tamẓẓit: {order}',
      legendSubgroups: { one: '{count} tagrawt tamẓẓit', other: '{count} n tgrawin timẓẓiyin' },
      legendHeadingInverse: 'Tasarut n ilwan: tiyugiwin n imgalnin',
      legendSelfInverse: 'amgal n iman nnes: {list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · afrdis {h} n urdr {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}, dɣa llant {n} / {size} = {count} n tiggayin',
      ringFootnote: 'Tella twrirt ɣf ufrdis arawsan, {id}.',
      ringFootnoteOrders: 'Tella twrirt ɣf ufrdis arawsan, {id}; amḍan imẓẓin n brra d urdr n yal afrdis.',
      svgAriaLabel: 'Amskan n taqlada n {group}',
      'notice.heading': 'War amsnulfu i {group}, dɣa war abrid ar iwwiḍ ɣr yal afrdis',
      'notice.body': 'Tagrawt ad tsɛa {count} n ifrdisn, mac war yan ufrdis ar iwwiḍ ɣr akk: abrid amqran sg 1 ar iṭṭf {longest} n isurifn. Tagrawt ad ittwasnlf sg tigrawin tisutlanin {factors}.',
      'notice.whyPowerOfTwo': 'Acku: n = {n} d tizmrt n 2 afella n 4.',
      'notice.whyFourAndOdd': 'Acku: n = {n} ar ittwabḍa s 4 d s yan umḍan amnzu afrdi.',
      'notice.whyTwoOddPrimes': 'Acku: n = {n} sɛa sin ifakturn imnza ifrdan imxtalfn.',
      'notice.rule': '(Z/n)* d tasutlant kigan ticki n d 1, 2 nɣ 4, nɣ tizmrt n umḍan amnzu afrdi p^k, nɣ snat n tikkal tizmrt ad, 2p^k. Tagrawt n usmrni Z/n d tasutlant yal ticki.',
      exportPng: 'Sider PNG n twrirt',
      exportSaved: 'Ittwaḥfḍ {filename}.',
      exportFailed: 'Asufɣ n tugna ur ikml g brawzr ad.'
    }
});
NT.i18n.register('site', {
    'zgh-Latn': {
      'nav.cyclicGroups': 'Tigrawin tisutlanin'
    }
});
NT.i18n.register('hub', {
    'zgh-Latn': {
      'card.cyclicGroups.title': 'Taqlada n tgrawt tasutlant',
      'card.cyclicGroups.desc': 'Yal afrdis n tgrawt ar ittuɣal d tnqqiḍt ɣ yat twrirt; ddu s umsnulfu, dɣa iwtarn ar d snlfn yan itri ar iṭṭf yal tnqqiḍt — ticki war yan ufrdis izmr ad iwwiḍ ɣr akk, tagrawt ar tbḍa ɣr twririn imẓẓin ayd ttwasnlf.'
    }
});
