/* 261009-tgw fragment: zh (merged into assets/i18n by plan 07) */
NT.i18n.register('cyclicGroups', {
    zh: {
      title: '循环群——项链可视化工具',
      eyebrow: '群论 · 生成元与轨道',
      heading: '循环群项链',
      lede: '选择一个群。每个元素均匀地排在一个圆环上。沿生成元前进就会画出弦，而存在一个能到达每个元素的生成元，正是这个群成为循环群的原因。没有这种元素的群，会被拆分为构成它的各个圆环。',
      xref: '在凯莱表中查看这个群的完整运算表 →',
      tablistLabel: '群运算',
      groupHeading: '群',
      subgroupHeading: '子群',
      identityOnly: '单位元只能生成它自己',
      nLabel: 'n——模数',
      genLabel: '显示的子群',
      nNoteClamped: 'n 的范围是 2 到 100，所以图中显示 n = {n}。',
      layersHeading: '图层',
      extraOptions: '显示更多选项',
      layerCord: '显示对应的多边形',
      layerGuide: '显示连接圆',
      layerElement: '前进路径',
      layerElementTitle: '前进一步，就是把当前元素与 {g} 组合',
      layerBackward: '禁用后退路径',
      layerPaths: '子群路径',
      resizeTitle: '拖动可调整大小；双击可重置',
      dirLabel: '前进方向',
      dirCw: '顺时针',
      dirCcw: '逆时针',
      sideInside: '内侧',
      sideOutside: '外侧',
      colorElement: '元素箭头颜色',
      colorInverse: '逆元箭头颜色',
      colorReset: '重置箭头颜色',
      genTop: '把所选生成元转到顶部',
      swapColors: '交换前进路径和后退路径的颜色',
      customColors: '手动选择箭头颜色',
      layerColors: '元素颜色',
      colorByLabel: '元素着色依据',
      colorByOrder: '子群的元素个数',
      colorByInverse: '逆元配对',
      layerOrders: '阶标签',
      layerBygen: '按生成元的幂排列元素',
      combineForward: '前进路径，用所选元素 {h} 来组合各元素',
      combineBackward: '后退路径，用所选元素的逆元来组合各元素，该逆元是 {hinv}',
      combineSelfInverse: '{h} 的逆元就是它自己，所以两条路径是同一条，只用两种颜色的混合色画一次',
      factsHeading: '这个群',
      cosetButton: '探索陪集',
      cosetHide: '停止探索陪集',
      cosetNoneGenerator: '没有可探索的陪集；{g} 是生成元',
      cosetProgress: '当前高亮第 {i} 个陪集，共 {count} 个',
      autoRotate: '自动旋转',
      autoRotateOff: '关',
      autoRotateCcw: '逆时针',
      autoRotateCw: '顺时针',
      rotateLabel: '旋转——拖动圆环',
      rotateBack: '逆时针旋转一个元素',
      rotateForward: '顺时针旋转一个元素',
      rotateValue: '旋转步数',
      rotateReset: '重置',
      subgroupsHeading: '每个元素生成的子群',
      autoShift: '自动移动循环子群',
      autoShiftTitle: '沿前进方向移动时，自动移动所生成的循环子群，使其与从顶部算起的第一个元素对齐',
      subLayoutLabel: '布局',
      subLayoutGrid: '网格',
      subLayoutList: '列表',
      'fact.group': '群',
      'fact.elements': '元素',
      'fact.identity': '单位元',
      'fact.operation': '运算',
      opAdd: '模 {n} 加法',
      opMul: '模 {n} 乘法',
      'fact.generators': '生成元',
      'fact.structure': '结构',
      factGeneratorsCount: '{order} 个中的 {count} 个',
      factGeneratorsNone: '0（不是循环群）',
      'hint.notCyclic': '没有任何元素能依次走遍其他所有元素：从 1 出发的箭头总是在圆环填满之前就回到原处。',
      'hint.noLabels': '这里的元素太小，放不下数字标签，但图案依然可见。',
      'hint.multiplicative': '元素是小于 {n} 且与 {n} 没有公因数的数。前进一步就是乘以 {g} 再取模 {n}。',
      'hint.additive': '前进一步就是加上 {g} 再取模 {n}。',
      'hint.mirror': '逆元之间以穿过单位元的虚线轴互为镜像；位于轴上的元素，其逆元就是它自己。',
      'hint.mirrorOffSorted': '元素按数值排序，所以这里的逆元不呈镜像。',
      'hint.mirrorOff': '在这种顺序下，元素按数值排序，所以逆元不呈镜像。打开“按生成元的幂排列元素”，就能看到它们以穿过单位元的轴互为镜像。',
      legendHeading: '颜色图例：子群的元素个数',
      legendOrder: '子群的元素个数：{order}',
      legendSubgroups: { other: '{count} 个子群' },
      legendHeadingInverse: '颜色图例：逆元配对',
      legendSelfInverse: '自逆元：{list}',
      legendPair: '{a} ↔ {b}',
      ringTitle: '{group} · 元素 {h}，阶为 {k}',
      cosetTitleAdd: '{a} + ⟨{h}⟩ = {set}',
      cosetTitleMul: '{a} · ⟨{h}⟩ = {set}',
      cosetCountAdd: '|⟨{h}⟩| = {n} / gcd({n}, {h}) = {n} / {d} = {size}，所以共有 {n} / {size} = {count} 个陪集',
      ringFootnote: '单位元 {id} 被圈了出来。',
      ringFootnoteOrders: '单位元 {id} 被圈了出来；外侧的小数字是各元素的阶。',
      svgAriaLabel: '{group} 的项链图',
      'notice.heading': '{group} 没有生成元，所以没有任何一条路径能走遍所有元素',
      'notice.body': '这个群有 {count} 个元素，但没有哪个元素能到达全部元素：从 1 出发最长的路径要走 {longest} 步。这个群由循环群 {factors} 构成。',
      'notice.whyPowerOfTwo': '原因：n = {n} 是大于 4 的 2 的幂。',
      'notice.whyFourAndOdd': '原因：n = {n} 能被 4 整除，也能被一个奇素数整除。',
      'notice.whyTwoOddPrimes': '原因：n = {n} 有两个不同的奇素因数。',
      'notice.rule': '(Z/n)* 是循环群，当且仅当 n 为 1、2 或 4，或为奇素数的幂 p^k，或为其两倍 2p^k。加法群 Z/n 总是循环群。',
      exportPng: '下载圆环 PNG',
      exportSaved: '已保存 {filename}。',
      exportFailed: '此浏览器无法导出图片。'
    }
});
NT.i18n.register('site', {
    zh: {
      'nav.cyclicGroups': '循环群'
    }
});
NT.i18n.register('hub', {
    zh: {
      'card.cyclicGroups.title': '循环群项链',
      'card.cyclicGroups.desc': '群中的每个元素都变成圆环上的一颗珠子；沿生成元前进，弦会描出一颗触及每颗珠子的星——而当没有任何单个元素能到达全部珠子时，这个群就会拆分成构成它的更小的圆环。'
    }
});
